package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun commuteRecommendationCases(): List<RecommendationCase> = listOf(
    commuteCase(1, "提前五分钟出门", "Leave five minutes early", "比平时早五分钟出发，让今天的路程不那么匆忙。", "Start five minutes earlier than usual for a less hurried journey."),
    commuteCase(2, "出门前检查随身物品", "Check your essentials", "确认手机、钥匙、钱包和交通卡都已带好。", "Make sure you have your phone, keys, wallet, and transit card."),
    commuteCase(3, "步行到下一站乘车", "Walk to the next stop", "时间允许时多走一站，再搭乘公共交通。", "When time allows, walk to the next stop before taking transit."),
    commuteCase(4, "提前一站下车", "Get off one stop early", "提前一站下车，用一小段步行结束今天的通勤。", "Get off one stop early and finish the commute with a short walk."),
    commuteCase(5, "走楼梯代替电梯", "Take the stairs", "在安全且体力允许时，用楼梯完成一段上下楼。", "When safe and comfortable, take the stairs for part of the way."),
    commuteCase(6, "给交通卡充值", "Top up your transit card", "检查交通卡余额，提前补足接下来几天需要的金额。", "Check your transit balance and add enough for the next few days."),
    commuteCase(7, "擦干净通勤水杯", "Clean your travel bottle", "清洗随身水杯，并在出门前装好饮用水。", "Clean your travel bottle and fill it before leaving."),
    commuteCase(8, "整理通勤背包", "Tidy your commute bag", "取出无用物品，只保留今天真正需要携带的东西。", "Remove unused items and keep only what you need today."),
    commuteCase(9, "戴好耳机再播放音乐", "Put on headphones before playing audio", "先确认耳机连接正常，避免声音影响周围的人。", "Check that your headphones are connected before playing audio."),
    commuteCase(10, "在站台安全线后等候", "Wait behind the safety line", "候车时与站台边缘保持距离，不低头向前走。", "Keep away from the platform edge and avoid walking while looking down."),
    commuteCase(11, "通勤时听一首新歌", "Listen to a new song", "选择一首没听过的歌，为熟悉的路程增加一点新鲜感。", "Choose an unfamiliar song to add something new to a familiar trip."),
    commuteCase(12, "听十分钟播客", "Listen to ten minutes of a podcast", "挑选一个轻松主题，在路上听完其中十分钟。", "Pick a light topic and listen to ten minutes during the journey."),
    commuteCase(13, "看一次窗外风景", "Look out the window", "暂时放下手机，观察沿途天空、树木和街道。", "Put away your phone briefly and notice the sky, trees, and streets."),
    commuteCase(14, "记录今天的出发时间", "Record your departure time", "记下实际出门时间，了解自己的通勤节奏。", "Note when you actually leave to better understand your routine."),
    commuteCase(15, "记录今天的到达时间", "Record your arrival time", "到达目的地后记下时间，算出今天的总路程时长。", "Note your arrival and calculate the total journey time."),
    commuteCase(16, "在路上做三次深呼吸", "Take three deep breaths", "遇到拥挤或等待时，用三次缓慢呼吸放松身体。", "Use three slow breaths to relax while waiting or in a crowd."),
    commuteCase(17, "通勤十分钟不看手机", "Avoid your phone for ten minutes", "留出十分钟不刷消息，让眼睛和注意力休息。", "Take a ten-minute break from messages to rest your eyes and attention."),
    commuteCase(18, "向司机说声谢谢", "Thank the driver", "下车时在合适的情况下向司机表达感谢。", "When appropriate, thank the driver as you get off."),
    commuteCase(19, "主动给下车的人让路", "Make room for exiting passengers", "上车前先站到一侧，让车内乘客顺利下车。", "Stand to one side and let passengers exit before you board."),
    commuteCase(20, "排队等待上车", "Queue before boarding", "按照现场顺序等候，不因赶时间打乱队伍。", "Wait in order without disrupting the line even when you are in a hurry."),
    commuteCase(21, "换一条街步行", "Walk along a different street", "在熟悉区域选择一条安全的新街道前往目的地。", "Choose a safe alternative street through a familiar area."),
    commuteCase(22, "换一个地铁入口", "Use a different subway entrance", "尝试离目的地更近的入口，比较实际步行距离。", "Try an entrance nearer your destination and compare the walking distance."),
    commuteCase(23, "乘坐一次不同线路", "Take a different transit line", "选择另一条可行线路，观察换乘次数和耗时变化。", "Use another viable line and compare transfers and travel time."),
    commuteCase(24, "步行完成一段短途", "Walk a short journey", "把一段距离不远的乘车路程改为步行。", "Replace a short ride with a walk."),
    commuteCase(25, "骑行完成一段通勤", "Cycle part of the commute", "选择安全路段骑行，并提前检查刹车和轮胎。", "Cycle along a safe section after checking the brakes and tires."),
    commuteCase(26, "尝试公交换地铁", "Combine bus and subway", "尝试一次公交与地铁组合，记录换乘是否顺畅。", "Combine bus and subway once and note how smooth the transfer feels."),
    commuteCase(27, "选择少走楼梯的路线", "Choose a route with fewer stairs", "携带重物时，提前找到电梯或缓坡路线。", "When carrying something heavy, plan a route with elevators or ramps."),
    commuteCase(28, "选择有遮雨处的路线", "Choose a sheltered route", "雨天优先经过连廊、屋檐或地下通道。", "On a rainy day, favor covered walkways or underground passages."),
    commuteCase(29, "寻找更安静的车厢", "Find a quieter carriage", "在不影响乘车的前提下，选择人相对少的位置。", "When practical, choose a less crowded part of the train."),
    commuteCase(30, "比较两条路线的耗时", "Compare two route times", "分别记录两条常用路线，看看哪条更稳定。", "Track two common routes and see which one is more reliable."),
    commuteCase(31, "观察一家沿途小店", "Notice a shop along the way", "留意一家平时忽略的小店，记住它售卖的东西。", "Notice a shop you usually pass and remember what it sells."),
    commuteCase(32, "拍一张清晨街景", "Photograph the morning street", "在安全停留的位置，拍下今天清晨的街道。", "From a safe stopping place, photograph the street this morning."),
    commuteCase(33, "留意今天的天空", "Notice today's sky", "抬头看看云层和光线，用一个词形容它。", "Look at the clouds and light, then describe the sky in one word."),
    commuteCase(34, "观察路边的一棵树", "Observe a roadside tree", "看看树叶、花朵或枝干最近发生了什么变化。", "Notice recent changes in the leaves, flowers, or branches."),
    commuteCase(35, "找到一处新的路标", "Find a new street sign", "留意一个以前没注意过的路牌或方向标识。", "Spot a street or direction sign you had not noticed before."),
    commuteCase(36, "记录一种街道声音", "Record a street sound", "留意车声、脚步声或鸟鸣，写下最清晰的一种。", "Notice traffic, footsteps, or birds and write down the clearest sound."),
    commuteCase(37, "看看沿途的早餐摊", "Notice breakfast stalls", "观察今天有哪些早餐摊开门，以及人们在买什么。", "See which breakfast stalls are open and what people are buying."),
    commuteCase(38, "发现一条安静小路", "Find a quiet side street", "在安全范围内留意一条人车较少的小路。", "Within a safe area, notice a side street with less traffic."),
    commuteCase(39, "寻找一个城市细节", "Find one city detail", "留意井盖、墙面、橱窗或建筑上的一个小设计。", "Notice a small design on a cover, wall, window, or building."),
    commuteCase(40, "记录一次日出或晚霞", "Record a sunrise or sunset", "遇到合适光线时，停在安全位置拍照或写一句话。", "When the light is right, stop safely for a photo or one sentence."),
    commuteCase(41, "雨天提前带伞", "Pack an umbrella for rain", "出门前查看天气，把雨伞放在方便拿取的位置。", "Check the weather and place an umbrella where it is easy to reach."),
    commuteCase(42, "晴天做好防晒", "Prepare for strong sunlight", "根据路程准备帽子、防晒用品或遮阳伞。", "Prepare a hat, sunscreen, or sunshade for the journey."),
    commuteCase(43, "降温时多带一件外套", "Carry an extra layer", "温差较大时带一件轻便外套，避免返程着凉。", "Bring a light layer when temperatures may drop before your return."),
    commuteCase(44, "炎热天气带足饮水", "Carry enough water in hot weather", "高温出行前装好水，并避免长时间暴晒。", "Fill your bottle before a hot journey and avoid prolonged sun exposure."),
    commuteCase(45, "大风天固定随身物品", "Secure belongings on a windy day", "收好帽子、文件和容易被风吹走的小物品。", "Secure hats, papers, and other items that wind could carry away."),
    commuteCase(46, "雾天穿醒目颜色", "Wear visible colors in fog", "能见度较低时选择容易被看见的衣物或配件。", "Wear clothing or accessories that are easier to see in low visibility."),
    commuteCase(47, "雨后绕开积水路段", "Avoid flooded paths after rain", "提前观察路面，选择干燥且不打滑的位置通行。", "Check the ground and choose a dry, non-slippery path."),
    commuteCase(48, "寒冷早晨提前热车", "Prepare the vehicle on a cold morning", "按车辆要求预留准备时间，并清理影响视线的雾气。", "Allow proper preparation time and clear anything blocking visibility."),
    commuteCase(49, "为突然下雨准备鞋套", "Pack shoe covers for sudden rain", "在包里放一双轻便鞋套，应对临时降雨。", "Keep lightweight shoe covers in your bag for unexpected rain."),
    commuteCase(50, "查看一次空气质量", "Check the air quality", "出门前查看空气情况，并按需要调整防护和路线。", "Check air conditions and adjust protection or route if needed."),
    commuteCase(51, "把常用证件放进固定夹层", "Store travel documents in one pocket", "为交通卡和证件设置固定位置，减少寻找时间。", "Give your card and documents a fixed pocket to reduce searching."),
    commuteCase(52, "给手机充足电", "Charge your phone", "出门前确认电量足够支持导航、联系和乘车。", "Ensure your phone has enough power for navigation, contact, and tickets."),
    commuteCase(53, "随身携带一包纸巾", "Carry a packet of tissues", "补充一小包纸巾，放在容易拿到的位置。", "Restock a small tissue packet and keep it within easy reach."),
    commuteCase(54, "准备一个备用口罩", "Pack a spare mask", "在包中放一个干净备用口罩，以备临时需要。", "Keep a clean spare mask in your bag for unexpected needs."),
    commuteCase(55, "带一份简单早餐", "Pack a simple breakfast", "来不及在家吃饭时，准备便于携带的早餐。", "When breakfast at home is not possible, pack something easy to carry."),
    commuteCase(56, "为数据线加收纳带", "Organize your charging cable", "卷好通勤包里的数据线，避免与其他物品缠绕。", "Coil the charging cable so it does not tangle with other items."),
    commuteCase(57, "清理包里的一张旧票据", "Remove an old receipt", "找出一张不再需要的票据，确认后妥善处理。", "Find one receipt you no longer need and dispose of it properly."),
    commuteCase(58, "准备一支随身笔", "Pack a pen", "在固定夹层放一支能正常书写的笔。", "Keep a working pen in a designated pocket."),
    commuteCase(59, "给钥匙加一个醒目标记", "Add a visible marker to your keys", "使用容易辨认的挂件，减少在包中寻找钥匙的时间。", "Use an easy-to-spot tag so your keys are quicker to find."),
    commuteCase(60, "每周清理一次通勤包", "Clean your commute bag weekly", "倒出全部物品，擦净内部后再按需要装回。", "Empty the bag, wipe the inside, and return only what you need."),
    commuteCase(61, "为让座留意周围乘客", "Watch for passengers who need a seat", "乘车时观察周围，在合适情况下主动让座。", "Notice nearby passengers and offer your seat when appropriate."),
    commuteCase(62, "帮助别人确认方向", "Help someone with directions", "遇到问路时，在自己确定的范围内清楚说明路线。", "When asked, explain the route clearly if you know it."),
    commuteCase(63, "扶住一次即将关闭的门", "Hold a safe door for someone", "在不会触碰车门或造成危险时，为身后的人扶住普通门。", "When safe, hold a regular door for the person behind you."),
    commuteCase(64, "不在车厢里外放声音", "Keep audio private on transit", "使用耳机并控制音量，为周围乘客保留安静空间。", "Use headphones at a moderate volume to preserve a quiet shared space."),
    commuteCase(65, "背包移到身前", "Move your backpack to the front", "车厢拥挤时把背包移到身前，避免碰到他人。", "In a crowded carriage, move your backpack forward to avoid bumping others."),
    commuteCase(66, "不堵住车门位置", "Keep doorways clear", "上车后向车厢内部移动，为其他乘客留出通道。", "Move farther inside after boarding so others can pass."),
    commuteCase(67, "咳嗽时做好遮挡", "Cover a cough properly", "使用纸巾或手肘遮挡，并及时清洁双手。", "Use a tissue or your elbow and clean your hands afterward."),
    commuteCase(68, "轻声接一次电话", "Take a call quietly", "必须接听时简短说明，并控制说话音量。", "If you must answer, keep the call brief and your voice low."),
    commuteCase(69, "为带行李的人留出空间", "Make space for luggage", "看到大件行李时适当调整站位，避免堵塞通道。", "Adjust your position around large luggage to keep the aisle open."),
    commuteCase(70, "对工作人员礼貌回应", "Respond politely to staff", "接受检查或引导时清楚回应，并表达感谢。", "Respond clearly during checks or guidance and say thank you."),
    commuteCase(71, "规划一条迟到备用路线", "Plan a backup route for delays", "保存一条替代线路，遇到延误时可以快速切换。", "Save an alternative route so you can switch quickly during delays."),
    commuteCase(72, "记住两个重要站点出口", "Learn two useful station exits", "确认常用目的地对应的出口，减少站内绕路。", "Match two common destinations with their exits to reduce detours."),
    commuteCase(73, "保存公司的完整地址", "Save your workplace address", "在手机中保存可复制的完整地址，方便导航和联系。", "Save a copyable full address for navigation and communication."),
    commuteCase(74, "下载一份离线地图", "Download an offline map", "为常去区域准备离线地图，应对网络不稳定。", "Download an offline map for common areas in case the network fails."),
    commuteCase(75, "设置一个出门提醒", "Set a leaving reminder", "根据预计路程设置提醒，给准备和下楼留出时间。", "Set an alert based on travel time, including time to get ready and leave."),
    commuteCase(76, "确认末班车时间", "Check the last departure", "晚归前查看末班车和末班地铁的准确时间。", "Before returning late, verify the final bus or train departure."),
    commuteCase(77, "准备一份紧急联系人信息", "Keep emergency contact details", "保存一位紧急联系人的电话，并确保锁屏时也能找到。", "Save an emergency contact and make it accessible when needed."),
    commuteCase(78, "记住附近的避雨地点", "Identify a nearby rain shelter", "在常走路线中找一处可以临时避雨的安全地点。", "Find a safe shelter along your usual route for sudden rain."),
    commuteCase(79, "为加班准备返程方案", "Plan a late return route", "提前比较公共交通、出租车和步行接驳的选择。", "Compare transit, taxi, and walking connections before working late."),
    commuteCase(80, "为手机准备移动电源", "Pack a power bank", "给移动电源充电并放入包中，应对长时间在外。", "Charge a power bank and pack it for a long day away."),
    commuteCase(81, "连续记录三天通勤时长", "Track commute time for three days", "记录三天的出发、到达和延误情况，寻找规律。", "Track departures, arrivals, and delays for three days to find patterns."),
    commuteCase(82, "找出最拥挤的十分钟", "Find the busiest ten-minute window", "比较不同出发时间，确认最容易拥堵的时段。", "Compare departure times to identify the most crowded period."),
    commuteCase(83, "测试早十分钟出发的效果", "Test leaving ten minutes earlier", "连续两天调整出发时间，比较拥挤程度和到达状态。", "Shift your departure for two days and compare crowds and arrival stress."),
    commuteCase(84, "计算一周通勤费用", "Calculate weekly commute costs", "汇总车费、骑行或停车支出，了解实际花费。", "Add transit, bike, or parking costs to understand the weekly total."),
    commuteCase(85, "比较步行与乘车时间", "Compare walking and riding time", "选择一段短路线，分别估算步行和乘车所需时间。", "Choose a short route and estimate the time needed by foot and by transit."),
    commuteCase(86, "减少一次不必要的换乘", "Remove one unnecessary transfer", "重新查看路线，尝试用多走几分钟换取少一次换乘。", "Review the route and trade a few minutes of walking for one less transfer."),
    commuteCase(87, "找出最稳定的通勤路线", "Find the most reliable route", "比较平均耗时和延误次数，而不只看最快记录。", "Compare average time and delay frequency rather than only the fastest trip."),
    commuteCase(88, "估算每月通勤支出", "Estimate monthly commute spending", "根据工作日数量和日均费用，算出大致月支出。", "Use workdays and daily costs to estimate your monthly spending."),
    commuteCase(89, "整理一份通勤改进清单", "Write a commute improvement list", "列出三个最影响体验的问题，并给每个问题写一个办法。", "List three main problems and one possible fix for each."),
    commuteCase(90, "完成一周准时出门挑战", "Complete a week of on-time departures", "连续五个工作日按计划出门，记录成功和偏差原因。", "Leave as planned for five workdays and note successes and delays."),
    commuteCase(91, "设计一条低碳通勤路线", "Design a low-carbon commute", "优先组合步行、骑行和公共交通，减少短途开车。", "Combine walking, cycling, and transit to reduce short car trips."),
    commuteCase(92, "完成一次全程步行通勤", "Complete a full walking commute", "在距离、天气和身体条件合适时，全程步行一次。", "When distance, weather, and health allow, walk the entire journey."),
    commuteCase(93, "完成一次全程骑行通勤", "Complete a full cycling commute", "提前规划安全车道，检查车辆并佩戴必要护具。", "Plan safe bike lanes, check the bicycle, and wear proper protection."),
    commuteCase(94, "组合三种出行方式", "Combine three travel modes", "尝试步行、公交和地铁组合，记录衔接是否合理。", "Combine walking, bus, and subway and evaluate each connection."),
    commuteCase(95, "为访客制作到达指南", "Create an arrival guide for a visitor", "写清路线、出口、地标和容易走错的位置。", "Explain the route, exit, landmarks, and places where mistakes are common."),
    commuteCase(96, "规划一条无障碍路线", "Plan an accessible route", "确认电梯、坡道和无障碍出口的位置与开放情况。", "Check elevators, ramps, and accessible exits and whether they are open."),
    commuteCase(97, "制定恶劣天气通勤方案", "Create a severe-weather commute plan", "为暴雨、大风或高温准备替代路线和必要物品。", "Prepare alternate routes and supplies for heavy rain, wind, or heat."),
    commuteCase(98, "完成一个月通勤复盘", "Review one month of commuting", "整理时间、费用和体验记录，找出最值得调整的一点。", "Review time, cost, and experience notes and choose one useful change."),
    commuteCase(99, "设计弹性出发时间表", "Design a flexible departure schedule", "为正常、拥堵和极端天气分别设定出门时间。", "Set separate departure times for normal, busy, and severe-weather days."),
    commuteCase(100, "完成一周综合通勤实验", "Run a one-week commute experiment", "一周内测试不同时间和路线，最后选出最适合自己的方案。", "Test different times and routes for a week, then choose the best plan."),
)

private fun commuteCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-commute-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_commute,
    imageAsset = "commute",
)
