package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun exploreRecommendationCases(): List<RecommendationCase> = listOf(
    exploreCase(1, "绕附近街区走一圈", "Walk around a nearby block", "选择熟悉安全的范围，用轻松速度看看周围。", "Choose a familiar safe area and look around at an easy pace."),
    exploreCase(2, "走一条没走过的小路", "Walk down an unfamiliar side street", "在安全区域选择一条新路，并留意如何返回。", "Choose a new street in a safe area and keep track of the way back."),
    exploreCase(3, "看看街角的小店", "Notice a shop on the corner", "观察店铺售卖什么，并记住它的名字。", "Notice what the shop sells and remember its name."),
    exploreCase(4, "拍一个特别的路牌", "Photograph an unusual street sign", "在不妨碍通行的位置记录一个有趣标识。", "Capture an interesting sign without blocking the path."),
    exploreCase(5, "寻找一棵特别的树", "Find an interesting tree", "观察树干、叶片或花朵与周围树木的不同。", "Notice how its trunk, leaves, or flowers differ from nearby trees."),
    exploreCase(6, "走到附近的路口", "Walk to a nearby intersection", "观察不同方向分别通往哪里，再沿原路返回。", "See where each direction leads, then return by the same route."),
    exploreCase(7, "发现一个安静角落", "Find a quiet corner", "在附近寻找一处人车较少且可以安全停留的位置。", "Find a nearby low-traffic place where you can pause safely."),
    exploreCase(8, "观察一栋建筑", "Observe one building", "看看它的窗户、入口、材料和整体形状。", "Notice its windows, entrance, materials, and overall form."),
    exploreCase(9, "寻找一种没见过的植物", "Find an unfamiliar plant", "只观察和拍照，不随意触碰或采摘。", "Observe and photograph it without touching or picking it."),
    exploreCase(10, "给附近地点写一句评价", "Write a one-line review of a nearby place", "用一句话记录环境、服务或最明显的感受。", "Record one clear impression about the setting, service, or experience."),
    exploreCase(11, "换一条路线去便利店", "Take a different route to a convenience store", "选择安全替代路线，比较沿途景物和距离。", "Use a safe alternative route and compare scenery and distance."),
    exploreCase(12, "走进一家没去过的小店", "Visit a shop you have never tried", "先浏览店内商品，再决定是否购买需要的东西。", "Browse first, then decide whether there is anything you actually need."),
    exploreCase(13, "尝一家新的早餐店", "Try a new breakfast place", "点一份简单招牌餐，记录味道和价格。", "Order a simple specialty and note its flavor and price."),
    exploreCase(14, "去一家陌生咖啡店", "Visit an unfamiliar coffee shop", "观察空间和菜单，选择一杯适合自己的饮品。", "Notice the space and menu, then choose a suitable drink."),
    exploreCase(15, "逛一家独立书店", "Browse an independent bookstore", "看看店内分类，并翻阅一本吸引你的书。", "Explore the sections and browse one book that catches your attention."),
    exploreCase(16, "参观一家文具店", "Visit a stationery shop", "寻找一种没用过的纸张、笔或收纳用品。", "Look for a type of paper, pen, or organizer you have not used."),
    exploreCase(17, "走进一家花店", "Step into a flower shop", "认识一种当季花材，并询问它的名称。", "Learn the name of one seasonal flower."),
    exploreCase(18, "逛一次小型超市", "Explore a small grocery store", "观察它与常去超市在商品选择上的不同。", "Notice how its product selection differs from your usual store."),
    exploreCase(19, "找一家本地甜品店", "Find a local dessert shop", "选择一份小份甜点，并记录最突出的口感。", "Choose a small dessert and note its strongest texture or flavor."),
    exploreCase(20, "发现一家适合再去的店", "Find a shop worth revisiting", "记录店名、位置以及你愿意再次到访的理由。", "Save its name, location, and the reason you would return."),
    exploreCase(21, "去附近公园散步", "Walk in a nearby park", "沿主要步道走一圈，并留意公共设施。", "Follow a main path and notice the available public facilities."),
    exploreCase(22, "坐一次公园长椅", "Sit on a park bench", "安静坐五分钟，观察周围的人、树和声音。", "Sit quietly for five minutes and notice people, trees, and sounds."),
    exploreCase(23, "寻找公园里的水景", "Find water in a park", "看看池塘、喷泉或溪流，并保持安全距离。", "Look for a pond, fountain, or stream and keep a safe distance."),
    exploreCase(24, "观察一只常见鸟类", "Observe a common bird", "留意它的颜色、叫声和移动方式，不投喂陌生食物。", "Notice its color, call, and movement without offering unsuitable food."),
    exploreCase(25, "记录公园里的三种颜色", "Record three colors in a park", "从植物、建筑和天空中各找一种颜色。", "Find one color each in plants, structures, and the sky."),
    exploreCase(26, "寻找一条林荫路", "Find a tree-lined path", "在树荫下慢走一段，留意光影变化。", "Walk slowly under the trees and notice changing light and shadow."),
    exploreCase(27, "看看公园导览图", "Read a park map", "了解入口、步道、卫生间和紧急出口的位置。", "Locate entrances, paths, restrooms, and emergency exits."),
    exploreCase(28, "走一座小桥", "Cross a small bridge", "在允许通行的桥上慢慢经过，并观察两侧景色。", "Cross an open bridge slowly and notice the view on both sides."),
    exploreCase(29, "寻找一片开阔草地", "Find an open lawn", "观察草地的用途和周围环境，不进入禁止区域。", "Notice how the lawn is used and stay outside restricted areas."),
    exploreCase(30, "完成一次三十分钟公园探索", "Explore a park for thirty minutes", "组合步行、观察和短暂休息，记录一个新发现。", "Combine walking, observation, and rest, then record one discovery."),
    exploreCase(31, "逛一次当地菜市场", "Visit a local food market", "观察当季食材，并记住一种以前没注意过的商品。", "Notice seasonal ingredients and one item you had not seen before."),
    exploreCase(32, "参观一次周末市集", "Visit a weekend market", "浏览不同摊位，并与一位摊主进行简短交流。", "Browse several stalls and have one brief conversation with a vendor."),
    exploreCase(33, "寻找一种本地小吃", "Find a local snack", "了解它的主要原料和常见吃法。", "Learn its main ingredients and how it is commonly eaten."),
    exploreCase(34, "观察一个手工作品摊位", "Observe a handmade-goods stall", "留意材料、制作方式和每件作品的差异。", "Notice the materials, techniques, and differences between pieces."),
    exploreCase(35, "询问一种陌生蔬菜", "Ask about an unfamiliar vegetable", "礼貌询问名称、产地或常见做法。", "Politely ask its name, origin, or common cooking method."),
    exploreCase(36, "比较两个摊位的商品", "Compare products from two stalls", "观察品种、价格和陈列方式的区别。", "Compare variety, price, and presentation."),
    exploreCase(37, "记录市场里最热闹的位置", "Find the busiest part of a market", "观察人流聚集的原因，并注意不妨碍通行。", "Notice why people gather there without blocking the flow."),
    exploreCase(38, "发现一种传统用品", "Find a traditional household item", "了解它过去和现在的使用方式。", "Learn how it was used in the past and how it is used now."),
    exploreCase(39, "拍一组市场颜色", "Photograph market colors", "征得允许后，记录三种鲜明的商品色彩。", "With permission where needed, capture three vivid product colors."),
    exploreCase(40, "完成一次市场观察笔记", "Write a market observation note", "记录环境、商品、人群和最有意思的发现。", "Note the setting, goods, people, and most interesting discovery."),
    exploreCase(41, "寻找一栋老建筑", "Find an older building", "查看公开信息，了解它的大致年代和用途。", "Use public information to learn its approximate age and purpose."),
    exploreCase(42, "观察一座现代建筑", "Observe a modern building", "留意外立面材料、线条和入口设计。", "Notice facade materials, lines, and entrance design."),
    exploreCase(43, "寻找一面街头壁画", "Find a street mural", "在公共区域欣赏作品，并记录最喜欢的部分。", "Enjoy it from a public area and note your favorite detail."),
    exploreCase(44, "观察一块历史标牌", "Read a historical marker", "完整阅读文字，记住一个新的时间或事件。", "Read it fully and remember one new date or event."),
    exploreCase(45, "寻找一处城市雕塑", "Find a public sculpture", "从不同角度观察，并了解作品名称。", "View it from different angles and learn its title."),
    exploreCase(46, "观察一种建筑门窗", "Study doors and windows", "比较同一街道上两栋建筑的门窗风格。", "Compare the door and window styles of two buildings on one street."),
    exploreCase(47, "寻找一个有趣的屋顶", "Find an interesting roof", "从公共空间观察屋顶形状和装饰。", "Observe its shape and decoration from a public space."),
    exploreCase(48, "记录一段街道历史", "Record one piece of street history", "查找可靠资料，写下街名或区域的由来。", "Use a reliable source to note how the street or area got its name."),
    exploreCase(49, "沿一条老街走一段", "Walk along an old street", "留意店铺、建筑和路面保留的历史痕迹。", "Notice historical traces in shops, buildings, and paving."),
    exploreCase(50, "完成一次建筑主题散步", "Take an architecture-themed walk", "选择三栋不同建筑，分别记录一个特点。", "Choose three different buildings and note one feature of each."),
    exploreCase(51, "参观一个免费展览", "Visit a free exhibition", "了解开放时间和规则，完整观看一个展区。", "Check opening times and rules, then explore one full section."),
    exploreCase(52, "去一次小型博物馆", "Visit a small museum", "选择一个展厅，记录最感兴趣的一件展品。", "Choose one gallery and note the exhibit that interests you most."),
    exploreCase(53, "参观一家画廊", "Visit an art gallery", "慢慢看完一组作品，并选出最喜欢的一幅。", "View one collection slowly and choose your favorite work."),
    exploreCase(54, "走进一座图书馆", "Visit a library", "查看楼层分布，并找到一个感兴趣的书架。", "Check the floor guide and find one shelf that interests you."),
    exploreCase(55, "参观一处文化馆", "Visit a cultural center", "了解它提供的展览、课程或公共活动。", "Learn about its exhibitions, classes, or public events."),
    exploreCase(56, "观看一次公共艺术作品", "View a public artwork", "了解创作者和作品背景，再写一句感受。", "Learn about the creator and context, then write one reaction."),
    exploreCase(57, "参加一次公开讲解", "Join a public guided talk", "听完后记录一个以前不知道的知识点。", "Record one fact you did not know before."),
    exploreCase(58, "领取一份场馆导览", "Pick up a venue guide", "按导览选择一条短路线完成参观。", "Use the guide to follow one short route through the venue."),
    exploreCase(59, "比较两件展品", "Compare two exhibits", "从材料、年代、用途或风格中选择两个角度比较。", "Compare them using two aspects such as material, age, use, or style."),
    exploreCase(60, "写一段参观记录", "Write a visit note", "用几句话记录地点、主题和最深印象。", "In a few sentences, note the place, theme, and strongest impression."),
    exploreCase(61, "乘公交到一个陌生站点", "Ride a bus to an unfamiliar stop", "提前查看返程路线，在安全区域短暂探索。", "Check the return route first and explore the safe area briefly."),
    exploreCase(62, "从一个新地铁出口出站", "Use a new subway exit", "查看出口地图，观察它连接到哪个街区。", "Check the exit map and see which neighborhood it reaches."),
    exploreCase(63, "坐一段平时不坐的公交", "Ride an unfamiliar bus route", "选择短距离路段，并持续留意当前位置。", "Choose a short segment and keep track of your location."),
    exploreCase(64, "步行连接两个地铁站", "Walk between two subway stations", "提前确认距离和路线，观察沿途街区变化。", "Check the distance and route, then notice changes between neighborhoods."),
    exploreCase(65, "骑行到附近公园", "Cycle to a nearby park", "检查车辆并选择安全道路，到达后短暂休息。", "Check the bicycle, use safe roads, and rest briefly on arrival."),
    exploreCase(66, "乘一次城市轮渡", "Take an urban ferry", "确认班次和安全要求，从公共区域观察水岸景色。", "Check the schedule and safety rules, then enjoy the waterfront view."),
    exploreCase(67, "体验一段共享单车路线", "Try a bike-share route", "确认车辆状态和停车区域，完成一段短途骑行。", "Check the bicycle and parking zones before a short ride."),
    exploreCase(68, "观察一个交通枢纽", "Observe a transport hub", "看看不同交通方式如何连接，并记住一条指引。", "Notice how different modes connect and remember one useful sign."),
    exploreCase(69, "比较两种到达方式", "Compare two ways to reach a place", "记录时间、费用、步行距离和舒适度。", "Compare time, cost, walking distance, and comfort."),
    exploreCase(70, "完成一次公共交通小环线", "Complete a small transit loop", "设计一条能返回起点的短路线，并提前确认末班时间。", "Plan a short loop back to the start and check final service times."),
    exploreCase(71, "拍三种不同的门", "Photograph three different doors", "寻找材质、颜色或年代不同的门进行记录。", "Find doors with different materials, colors, or ages."),
    exploreCase(72, "寻找五个城市数字", "Find five city numbers", "从门牌、公交、路标或建筑中收集五个数字。", "Collect five numbers from addresses, transit, signs, or buildings."),
    exploreCase(73, "拍一组圆形物品", "Photograph circular objects", "在公共空间寻找三个不同用途的圆形。", "Find three circles serving different purposes in public spaces."),
    exploreCase(74, "记录街道的三种声音", "Record three street sounds", "分别留意交通、人群和自然环境中的声音。", "Notice one sound each from traffic, people, and nature."),
    exploreCase(75, "寻找一条颜色主题路线", "Follow a color-themed route", "选择一种颜色，沿路寻找五个对应物品。", "Choose one color and find five matching objects along the way."),
    exploreCase(76, "拍一组城市影子", "Photograph city shadows", "利用建筑、树木和路灯形成的影子完成三张照片。", "Capture three shadows made by buildings, trees, or streetlights."),
    exploreCase(77, "寻找三个不同材质的墙面", "Find three wall textures", "观察砖、石、木或金属表面的差异。", "Compare surfaces made from brick, stone, wood, or metal."),
    exploreCase(78, "记录一个街区的气味", "Notice a neighborhood scent", "描述食物、植物或雨后空气带来的气味。", "Describe a scent from food, plants, or air after rain."),
    exploreCase(79, "完成一次十张街景挑战", "Complete a ten-photo street challenge", "每张照片记录一个不同细节，避免重复主题。", "Capture a different detail in every photo without repeating themes."),
    exploreCase(80, "制作一页街区观察册", "Create a neighborhood observation page", "组合照片、路线和简短文字，记录一次散步。", "Combine photos, a route, and brief notes from one walk."),
    exploreCase(81, "去一次城市边缘的公园", "Visit a park near the city edge", "提前规划交通和返程，在开放区域内活动。", "Plan transport and return travel, and remain within open areas."),
    exploreCase(82, "探访一个邻近街区", "Explore a neighboring district", "选择一个主要地点作为目标，并在周边步行观察。", "Choose one main destination and walk around its surroundings."),
    exploreCase(83, "安排一次半日城市漫游", "Plan a half-day city wander", "确定起点、休息点和返程时间，保留自由探索空间。", "Set a start, rest point, and return time while leaving room to wander."),
    exploreCase(84, "沿河或湖走一段", "Walk along a river or lake", "选择开放步道，远离危险水域并留意天气。", "Use an open path, stay away from unsafe water, and watch the weather."),
    exploreCase(85, "参观一个邻近小镇", "Visit a nearby town", "提前了解交通、主要街区和返程班次。", "Research transport, central areas, and return schedules in advance."),
    exploreCase(86, "体验一次郊野步道", "Try a countryside trail", "选择适合体力的正规路线，准备水和基础用品。", "Choose an official route suited to your ability and carry water and essentials."),
    exploreCase(87, "寻找一个城市观景点", "Find a city viewpoint", "通过正规开放路线到达，并遵守现场安全规定。", "Use an officially open route and follow all safety rules."),
    exploreCase(88, "完成一次日出探索", "Take a sunrise outing", "提前确认天气、交通和安全地点，并结伴前往更稳妥。", "Check weather, transport, and a safe location; going with company is preferable."),
    exploreCase(89, "完成一次夜间街区观察", "Explore a neighborhood at night", "选择照明良好且熟悉的区域，控制时间并注意返程。", "Stay in a familiar well-lit area, limit the duration, and plan the return."),
    exploreCase(90, "策划一次周末微旅行", "Plan a weekend micro-trip", "选择近距离目的地，安排交通、预算、餐食和返程。", "Choose a nearby destination and plan transport, budget, food, and return."),
    exploreCase(91, "为朋友设计一条散步路线", "Design a walking route for a friend", "结合对方兴趣，安排三个地点和一个休息点。", "Match their interests with three stops and one rest point."),
    exploreCase(92, "制作一份本地探索清单", "Create a local exploration list", "列出十个没去过但愿意尝试的附近地点。", "List ten nearby places you have not visited but would like to try."),
    exploreCase(93, "连续七天发现一个新细节", "Find one new detail for seven days", "每天在熟悉路线记录一个以前忽略的事物。", "Notice one previously overlooked detail on a familiar route each day."),
    exploreCase(94, "绘制一张个人街区地图", "Draw a personal neighborhood map", "标出常去地点、安全路线和想探索的区域。", "Mark common destinations, safe routes, and areas to explore."),
    exploreCase(95, "完成一次城市主题摄影", "Complete a city photo theme", "选择建筑、招牌或交通等主题，拍摄一组完整照片。", "Choose architecture, signs, or transport and create a complete photo set."),
    exploreCase(96, "研究一个街区的历史", "Research a neighborhood's history", "使用可靠资料整理年代、变化和代表地点。", "Use reliable sources to summarize its era, changes, and notable places."),
    exploreCase(97, "制定一份四周探索计划", "Create a four-week exploration plan", "每周安排一个不同主题，并控制时间和预算。", "Assign a different theme each week while managing time and budget."),
    exploreCase(98, "完成一次无导航短途探索", "Take a short no-navigation walk", "仅在熟悉安全区域尝试，并记住明显地标和返回方向。", "Try this only in a familiar safe area and track landmarks and the return direction."),
    exploreCase(99, "制作一份城市体验指南", "Create a personal city guide", "整理五个地点的路线、特色、费用和注意事项。", "Document routes, highlights, costs, and notes for five places."),
    exploreCase(100, "完成一个月本地探索挑战", "Complete a one-month local exploration challenge", "每周体验一个新地点，记录照片、路线、花费和感受。", "Visit one new place each week and record photos, route, cost, and impressions."),
)

private fun exploreCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-explore-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_explore,
    imageAsset = "explore",
)
