package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun foodRecommendationCases(): List<RecommendationCase> = listOf(
    foodCase(1, "吃一份黄焖鸡米饭", "Enjoy a braised chicken rice meal", "选一家喜欢的小店，认真吃完这份热乎的米饭。", "Choose a favorite shop and enjoy the warm meal without rushing."),
    foodCase(2, "煮一碗番茄鸡蛋面", "Cook tomato and egg noodles", "用番茄、鸡蛋和面条做一顿简单的热食。", "Make a simple hot meal with tomatoes, eggs, and noodles."),
    foodCase(3, "吃一个当季水果", "Eat a seasonal fruit", "挑一个正当季的水果，记录它的甜度和口感。", "Choose a fruit in season and note its sweetness and texture."),
    foodCase(4, "做一份煎蛋早餐", "Make a fried-egg breakfast", "煎一个鸡蛋，搭配主食完成今天的早餐。", "Fry an egg and pair it with a staple food for breakfast."),
    foodCase(5, "泡一杯绿茶", "Brew a cup of green tea", "控制好水温，慢慢喝完一杯清香的绿茶。", "Use a suitable water temperature and slowly enjoy the tea."),
    foodCase(6, "给午餐加一份青菜", "Add greens to lunch", "为今天的午餐补充一份清淡的绿色蔬菜。", "Add a light green vegetable dish to today's lunch."),
    foodCase(7, "烤两片吐司", "Toast two slices of bread", "把吐司烤到微脆，搭配喜欢的酱料食用。", "Toast the bread until lightly crisp and add a spread you like."),
    foodCase(8, "认真吃一顿晚饭", "Eat dinner mindfully", "暂时放下手机，把注意力放在食物和饱腹感上。", "Put away your phone and focus on the food and how full you feel."),
    foodCase(9, "做一杯水果酸奶", "Make a fruit yogurt cup", "切一点水果放进酸奶里，做一份清爽的小食。", "Add chopped fruit to yogurt for a refreshing snack."),
    foodCase(10, "尝一家附近的小店", "Try a nearby eatery", "走进一家没吃过的小店，点一份招牌餐。", "Visit a nearby place you have not tried and order its specialty."),
    foodCase(11, "蒸一个红薯", "Steam a sweet potato", "蒸熟一个红薯，把它作为早餐或下午加餐。", "Steam a sweet potato for breakfast or an afternoon snack."),
    foodCase(12, "煮一锅小米粥", "Cook millet porridge", "用小火煮一锅温和的小米粥，留意浓稠程度。", "Simmer a gentle millet porridge and notice its consistency."),
    foodCase(13, "做一份蔬菜沙拉", "Make a vegetable salad", "选择三种蔬菜，搭配简单酱汁拌匀。", "Choose three vegetables and toss them with a simple dressing."),
    foodCase(14, "喝一杯温牛奶", "Drink warm milk", "把牛奶加热到适口温度，慢慢喝完。", "Warm the milk to a comfortable temperature and drink it slowly."),
    foodCase(15, "煮两个水煮蛋", "Boil two eggs", "掌握好时间，做出自己喜欢的蛋黄熟度。", "Time the eggs to get the yolks just how you like them."),
    foodCase(16, "做一份蛋炒饭", "Make egg fried rice", "利用剩米饭和鸡蛋，快速完成一顿饭。", "Use leftover rice and eggs to make a quick meal."),
    foodCase(17, "吃一碗清汤馄饨", "Have wontons in clear soup", "选择清淡汤底，感受馄饨皮和馅料的口感。", "Choose a light broth and enjoy the wrappers and filling."),
    foodCase(18, "冲一杯燕麦片", "Prepare a bowl of oatmeal", "用热水或牛奶冲泡燕麦，加入少量水果。", "Prepare oats with hot water or milk and add a little fruit."),
    foodCase(19, "做一根烤玉米", "Roast an ear of corn", "把玉米烤热，品尝它自然的香甜味。", "Roast the corn and enjoy its natural sweetness."),
    foodCase(20, "吃一份豆浆油条", "Have soy milk and a fried dough stick", "找一家早餐店，体验一次经典中式早餐。", "Visit a breakfast shop for this classic Chinese pairing."),
    foodCase(21, "切一盘苹果", "Slice an apple", "把苹果切成方便入口的小块，与身边的人分享。", "Cut an apple into bite-size pieces and share it with someone."),
    foodCase(22, "做一份凉拌黄瓜", "Make a cucumber salad", "拍碎黄瓜，加入简单调味料拌匀。", "Smash a cucumber and toss it with simple seasonings."),
    foodCase(23, "煮一碗紫菜蛋花汤", "Cook seaweed egg-drop soup", "用十分钟做一碗清淡又温暖的汤。", "Make a light and warming soup in ten minutes."),
    foodCase(24, "吃一小把坚果", "Eat a small handful of nuts", "控制好分量，把坚果作为今天的加餐。", "Keep the portion modest and enjoy the nuts as a snack."),
    foodCase(25, "做一份火腿三明治", "Make a ham sandwich", "用面包、火腿和蔬菜组合一份简单三明治。", "Combine bread, ham, and vegetables into a simple sandwich."),
    foodCase(26, "煮一杯热可可", "Make a cup of hot cocoa", "调一杯不过分甜的热可可，趁热饮用。", "Prepare a mildly sweet hot cocoa and enjoy it warm."),
    foodCase(27, "吃一碗白粥配小菜", "Have rice porridge with side dishes", "选择一两样清淡小菜，配一碗温热白粥。", "Pair warm rice porridge with one or two light side dishes."),
    foodCase(28, "烤一个小土豆", "Bake a small potato", "把土豆烤到软糯，只加少量盐调味。", "Bake the potato until tender and season it lightly with salt."),
    foodCase(29, "做一份香蕉奶昔", "Make a banana smoothie", "用香蕉和牛奶搅打一杯顺滑饮品。", "Blend banana and milk into a smooth drink."),
    foodCase(30, "尝一种新口味的面包", "Try a new kind of bread", "从面包店选一种没吃过的口味，记录第一印象。", "Choose an unfamiliar bread and record your first impression."),
    foodCase(31, "做一盘西红柿炒鸡蛋", "Cook tomatoes with scrambled eggs", "完成一道经典家常菜，调整到自己喜欢的酸甜度。", "Cook this classic home dish and balance the sweet and sour flavors."),
    foodCase(32, "煮一份速冻饺子", "Cook frozen dumplings", "注意水开和点水的时机，把饺子完整煮熟。", "Watch the boiling and timing so the dumplings cook through intact."),
    foodCase(33, "做一碗葱油拌面", "Make scallion oil noodles", "用葱油和酱汁拌匀面条，趁热食用。", "Toss noodles with scallion oil and sauce, then serve them hot."),
    foodCase(34, "蒸一碗鸡蛋羹", "Steam a savory egg custard", "控制蛋液和水的比例，蒸出细嫩口感。", "Balance the egg and water to create a silky texture."),
    foodCase(35, "做一盘清炒时蔬", "Stir-fry seasonal vegetables", "选择一种时令蔬菜，用简单调味快速炒熟。", "Quickly stir-fry one seasonal vegetable with light seasoning."),
    foodCase(36, "煎一块豆腐", "Pan-fry a piece of tofu", "把豆腐两面煎到金黄，再加入少量酱汁。", "Pan-fry both sides until golden and add a little sauce."),
    foodCase(37, "煮一锅玉米排骨汤", "Cook corn and pork rib soup", "用小火慢炖，让玉米的甜味进入汤里。", "Simmer gently so the sweetness of the corn flavors the soup."),
    foodCase(38, "做一份土豆丝", "Cook shredded potatoes", "把土豆切成细丝，炒出爽脆口感。", "Cut the potato into thin strips and keep them pleasantly crisp."),
    foodCase(39, "包一份生菜饭", "Make a lettuce rice wrap", "用生菜包住米饭和少量配菜，一口吃下。", "Wrap rice and a small filling in lettuce for an easy bite."),
    foodCase(40, "做一份鸡胸肉餐", "Prepare a chicken breast meal", "搭配蔬菜和主食，让这顿饭简单又均衡。", "Pair chicken breast with vegetables and a staple for a balanced meal."),
    foodCase(41, "吃一顿不加辣的饭", "Have a non-spicy meal", "暂时避开辛辣调味，感受食材本身的味道。", "Skip spicy seasoning and notice the ingredients' natural flavors."),
    foodCase(42, "尝一次少盐午餐", "Try a lower-salt lunch", "减少重口味酱料，观察自己是否依然吃得满足。", "Use less salty sauce and see whether the meal still feels satisfying."),
    foodCase(43, "准备一份健康便当", "Prepare a balanced lunch box", "装入主食、蛋白质和蔬菜，带去上班或上学。", "Pack a staple, protein, and vegetables for work or school."),
    foodCase(44, "用水果替代一次甜点", "Replace dessert with fruit", "饭后选一份水果，暂时不吃高糖甜点。", "Choose fruit after the meal instead of a sugary dessert."),
    foodCase(45, "喝一杯无糖饮料", "Choose a sugar-free drink", "选择白水、茶或无糖咖啡，减少一次额外糖分。", "Choose water, tea, or unsweetened coffee to skip extra sugar."),
    foodCase(46, "吃到七分饱", "Stop eating when comfortably full", "放慢进食速度，在感到舒适时停下来。", "Slow down and stop when you feel comfortably satisfied."),
    foodCase(47, "为今天准备两种蔬菜", "Prepare two vegetables today", "选择不同颜色的蔬菜，让餐盘更丰富。", "Choose vegetables of different colors to vary your plate."),
    foodCase(48, "自己调一份沙拉汁", "Mix a homemade salad dressing", "用醋、油和少量调味料调出喜欢的比例。", "Mix vinegar, oil, and light seasonings in a ratio you enjoy."),
    foodCase(49, "吃一份高蛋白早餐", "Have a protein-rich breakfast", "在早餐中加入鸡蛋、牛奶、豆制品或肉类。", "Include eggs, milk, soy foods, or meat in your breakfast."),
    foodCase(50, "准备一壶柠檬水", "Prepare lemon water", "切几片新鲜柠檬泡水，作为今天的日常饮品。", "Infuse water with fresh lemon slices for today's regular drink."),
    foodCase(51, "复刻一道家常菜", "Recreate a family dish", "回忆熟悉的味道，试着做出一道常吃的菜。", "Recall a familiar flavor and recreate a dish you often eat."),
    foodCase(52, "向家人学一道菜", "Learn a dish from family", "请家人讲解步骤，并亲手完成其中一部分。", "Ask a family member for the steps and cook part of it yourself."),
    foodCase(53, "做一道小时候爱吃的饭", "Cook a childhood favorite", "选择一道带有回忆的食物，记录它让你想到什么。", "Choose a nostalgic dish and note what memories it brings back."),
    foodCase(54, "给家人盛一碗汤", "Serve soup to a family member", "吃饭时主动为家人盛汤，享受一起用餐的时刻。", "Serve soup to a family member and enjoy the shared meal."),
    foodCase(55, "和朋友分享一份小吃", "Share a snack with a friend", "选一份适合分享的小吃，边吃边聊近况。", "Choose an easy-to-share snack and catch up while eating."),
    foodCase(56, "为同事带一份水果", "Bring fruit for a colleague", "准备一份干净方便的水果，与同事一起分享。", "Prepare clean, convenient fruit and share it with a colleague."),
    foodCase(57, "请朋友推荐一家餐馆", "Ask a friend for a restaurant recommendation", "听取朋友的推荐，记下一家以后想尝试的店。", "Take a friend's suggestion and save one place to try later."),
    foodCase(58, "和家人一起包饺子", "Make dumplings with family", "分工准备馅料和饺子皮，一起完成一顿饭。", "Divide the filling and wrapping work to make a meal together."),
    foodCase(59, "准备一份双人早餐", "Prepare breakfast for two", "多做一份早餐，邀请身边的人一起吃。", "Make an extra serving and invite someone nearby to join you."),
    foodCase(60, "交换一次拿手菜", "Exchange signature dishes", "和朋友各做一道擅长的菜，互相品尝并交流做法。", "Cook signature dishes with a friend, taste them, and exchange tips."),
    foodCase(61, "尝一种地方特色小吃", "Try a local specialty snack", "选择一种有地域特色的小吃，了解它的主要原料。", "Try a regional snack and learn about its main ingredients."),
    foodCase(62, "吃一次街边早餐", "Have breakfast from a street vendor", "选一家干净的小摊，体验当地常见的早餐。", "Choose a clean vendor and try a common local breakfast."),
    foodCase(63, "逛一次菜市场", "Visit a food market", "观察当季食材和价格，挑一样带回家。", "Look at seasonal ingredients and prices, then bring one item home."),
    foodCase(64, "尝一碗不同做法的面", "Try noodles made a different way", "选择一种平时少吃的面食，比较口感和汤底。", "Choose an unfamiliar noodle style and compare its texture and broth."),
    foodCase(65, "买一份现烤点心", "Buy a freshly baked pastry", "挑一份刚出炉的小点心，趁新鲜品尝。", "Pick a pastry fresh from the oven and enjoy it while fresh."),
    foodCase(66, "尝一种新的调味酱", "Try a new condiment", "在少量食物上试用新酱料，记录它适合搭配什么。", "Test a new sauce on a small portion and note what it pairs with."),
    foodCase(67, "喝一杯手冲咖啡", "Drink a pour-over coffee", "选择一种咖啡豆，感受它的香气、酸度和余味。", "Choose one coffee bean and notice its aroma, acidity, and finish."),
    foodCase(68, "体验一次素食午餐", "Try a vegetarian lunch", "不使用肉类，搭配豆制品和蔬菜完成一餐。", "Build a meat-free meal with soy foods and vegetables."),
    foodCase(69, "尝一款异国料理", "Try a cuisine from another country", "选择一种不熟悉的料理，了解其中一道菜的吃法。", "Choose an unfamiliar cuisine and learn how one dish is eaten."),
    foodCase(70, "去一家老字号吃饭", "Visit a long-established restaurant", "点一道经典菜，留意它为什么能被长期保留。", "Order a classic dish and consider why it has endured."),
    foodCase(71, "按食谱做一道新菜", "Cook a new recipe", "完整阅读食谱后再动手，按步骤完成第一次尝试。", "Read the whole recipe first, then follow each step for your first attempt."),
    foodCase(72, "做一份低糖饼干", "Bake lower-sugar cookies", "适当减少糖量，观察成品的口感和香气变化。", "Reduce the sugar and observe how the texture and aroma change."),
    foodCase(73, "烤一个六寸蛋糕", "Bake a small cake", "准备好材料和模具，独立完成搅拌、烘烤与脱模。", "Prepare the ingredients and pan, then mix, bake, and unmold it yourself."),
    foodCase(74, "做一份手工披萨", "Make a homemade pizza", "铺好面饼、酱料和配菜，烤出一份自己的搭配。", "Layer dough, sauce, and toppings to bake your own combination."),
    foodCase(75, "腌一罐酸甜萝卜", "Pickle sweet-and-sour radish", "切好萝卜并调配腌汁，冷藏后再品尝。", "Slice the radish, mix the brine, and chill it before tasting."),
    foodCase(76, "做一锅番茄炖牛腩", "Cook tomato beef stew", "预留充足时间慢炖，让牛肉变软并吸收汤汁。", "Allow enough time for the beef to become tender and absorb the sauce."),
    foodCase(77, "自己揉面做馒头", "Make steamed buns from scratch", "完成和面、发酵、整形和蒸制，观察面团变化。", "Mix, proof, shape, and steam the dough while watching how it changes."),
    foodCase(78, "尝试做一次寿司卷", "Make a sushi roll", "准备米饭和简单配料，卷紧后切成整齐小段。", "Prepare rice and simple fillings, roll firmly, and slice evenly."),
    foodCase(79, "熬一小锅草莓酱", "Cook a small batch of strawberry jam", "用草莓和少量糖慢煮，装入干净容器保存。", "Simmer strawberries with a little sugar and store the jam in a clean jar."),
    foodCase(80, "做一桌三菜一汤", "Prepare three dishes and a soup", "提前安排菜单和顺序，让几道菜尽量同时完成。", "Plan the menu and cooking order so everything finishes close together."),
    foodCase(81, "清点冰箱里的食材", "Take inventory of the refrigerator", "查看保质期，把需要尽快食用的食材放到前面。", "Check dates and move ingredients that should be used soon to the front."),
    foodCase(82, "用剩米饭做一顿饭", "Make a meal with leftover rice", "合理利用剩米饭，确保充分加热后再食用。", "Use leftover rice wisely and reheat it thoroughly before eating."),
    foodCase(83, "用三种剩余食材做菜", "Cook with three leftover ingredients", "从现有食材出发设计一道菜，减少不必要的浪费。", "Design a dish around three ingredients you already have to reduce waste."),
    foodCase(84, "整理一次调味料", "Organize the seasonings", "擦净瓶身并检查日期，把常用调料放在顺手位置。", "Clean the containers, check dates, and place common seasonings within reach."),
    foodCase(85, "规划明天的三餐", "Plan tomorrow's meals", "根据现有食材列出简单菜单，避免临时纠结。", "Use what you have to make a simple menu and avoid last-minute decisions."),
    foodCase(86, "列一份一周采购清单", "Write a weekly grocery list", "先检查库存，再按蔬菜、肉类和主食分类记录。", "Check your supplies first, then group the list by produce, protein, and staples."),
    foodCase(87, "分装三份工作日午餐", "Pack three weekday lunches", "一次准备并分装三份午餐，冷藏保存并标注日期。", "Prepare and portion three lunches, refrigerate them, and label the dates."),
    foodCase(88, "比较两种咖啡豆", "Compare two coffee beans", "用相同方法冲泡两种豆子，记录香气和味道差异。", "Brew two beans the same way and compare their aromas and flavors."),
    foodCase(89, "测试同一道菜的两种做法", "Test two methods for one dish", "改变一个关键步骤，比较两份成品的口感。", "Change one key step and compare the textures of the two results."),
    foodCase(90, "设计一份家庭周末菜单", "Design a family weekend menu", "考虑人数、口味和准备时间，安排完整的一餐。", "Consider the group size, preferences, and prep time to plan a full meal."),
    foodCase(91, "学习正确使用菜刀", "Practice safe knife skills", "练习稳定握刀和切配姿势，全程注意手指安全。", "Practice a stable grip and cutting posture while keeping your fingers safe."),
    foodCase(92, "学习判断肉类熟度", "Learn to judge meat doneness", "了解适合的中心温度，确保肉类熟透且不过度加热。", "Learn suitable internal temperatures so the meat is safe but not overcooked."),
    foodCase(93, "给常做的菜写下配方", "Write down a favorite recipe", "记录食材用量和关键步骤，下次可以稳定复现。", "Record quantities and key steps so you can reproduce the dish reliably."),
    foodCase(94, "为朋友设计一份小菜单", "Design a small menu for a friend", "根据朋友的口味和忌口，安排主食、菜和饮品。", "Plan a staple, dishes, and a drink around your friend's tastes and restrictions."),
    foodCase(95, "完成一次盲测品尝", "Do a blind taste test", "遮住包装比较两种相似食物，记录真实偏好。", "Hide the packaging, compare two similar foods, and record your honest preference."),
    foodCase(96, "研究一道菜的营养组成", "Study a dish's nutrition", "拆分主要食材，了解其中的蛋白质、碳水和脂肪来源。", "Break down the ingredients and identify the protein, carbohydrate, and fat sources."),
    foodCase(97, "挑战一顿只用一个锅", "Cook a one-pot meal", "设计合理的下锅顺序，用一个锅完成整顿饭。", "Plan the cooking order and complete the whole meal in one pot."),
    foodCase(98, "做一顿预算内晚餐", "Cook dinner on a budget", "先设定预算，再选择食材完成营养均衡的一餐。", "Set a budget first, then choose ingredients for a balanced dinner."),
    foodCase(99, "复刻餐馆里喜欢的一道菜", "Recreate a restaurant favorite", "分析主要味道和做法，在家完成一次接近原版的尝试。", "Analyze the main flavors and method, then try to recreate the dish at home."),
    foodCase(100, "策划一次四人主题晚餐", "Plan a themed dinner for four", "确定主题、菜单、采购清单和时间安排，并邀请三位朋友参加。", "Choose a theme, menu, shopping list, and schedule, then invite three friends."),
)

private fun foodCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-food-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_food,
    imageAsset = "food",
)
