package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun funRecommendationCases(): List<RecommendationCase> = listOf(
    funCase(1, "听一首喜欢的歌", "Listen to a favorite song", "暂时放下其他事情，完整听完一首喜欢的歌。", "Pause everything else and listen to one favorite song from start to finish."),
    funCase(2, "看一段喜剧短片", "Watch a comedy clip", "找一段轻松的喜剧内容，让自己笑一会儿。", "Find a light comedy clip and give yourself a moment to laugh."),
    funCase(3, "玩一局休闲游戏", "Play one casual game", "选择一局时间较短的游戏，结束后及时停下。", "Choose a short casual game and stop when the round ends."),
    funCase(4, "画一张随手涂鸦", "Make a quick doodle", "不用考虑画得好不好，随意画满一小张纸。", "Ignore whether it looks good and freely fill a small sheet of paper."),
    funCase(5, "读一个短篇故事", "Read a short story", "选一篇能在短时间读完的故事，留意最喜欢的段落。", "Choose a story you can finish quickly and notice your favorite passage."),
    funCase(6, "唱一首熟悉的歌", "Sing a familiar song", "跟着伴奏或清唱，把一首熟悉的歌完整唱完。", "Use a backing track or sing unaccompanied and finish a familiar song."),
    funCase(7, "拍一张有趣的照片", "Take an amusing photo", "用特别的角度记录身边一个普通物品。", "Photograph an ordinary nearby object from an unusual angle."),
    funCase(8, "看一集轻松动画", "Watch one light animated episode", "挑选一集节奏轻松的动画，专心看完。", "Choose a relaxed animated episode and watch it without distraction."),
    funCase(9, "猜一道脑筋急转弯", "Solve a brain teaser", "找一道简单题目，先自己思考再查看答案。", "Find a simple brain teaser and think before checking the answer."),
    funCase(10, "折一架纸飞机", "Fold a paper airplane", "用一张废纸折出纸飞机，并试飞一次。", "Use scrap paper to fold an airplane and test it once."),
    funCase(11, "听一张完整专辑", "Listen to a full album", "按原有顺序听完整张专辑，选出最喜欢的一首。", "Listen in track order and choose the song you like most."),
    funCase(12, "重温一首童年歌曲", "Revisit a childhood song", "找一首小时候常听的歌，记录它带来的回忆。", "Find a song from childhood and note the memory it brings back."),
    funCase(13, "整理一份通勤歌单", "Build a commute playlist", "选十首适合路上听的歌，调整成顺畅的播放顺序。", "Choose ten songs for commuting and arrange them into a smooth sequence."),
    funCase(14, "听一场现场演出录音", "Listen to a live performance recording", "比较现场版本和录音室版本带来的不同感受。", "Compare how the live version feels against the studio recording."),
    funCase(15, "发现一位新歌手", "Discover a new singer", "试听一位陌生歌手的三首作品，记下第一印象。", "Try three songs by an unfamiliar singer and record your first impression."),
    funCase(16, "学唱一段副歌", "Learn a song chorus", "反复听一小段副歌，尝试跟上歌词和节奏。", "Replay a short chorus and try to follow the lyrics and rhythm."),
    funCase(17, "用桌面敲一段节奏", "Tap out a rhythm", "用手指敲出四小节节奏，并重复三次。", "Tap a four-bar rhythm with your fingers and repeat it three times."),
    funCase(18, "听十分钟纯音乐", "Listen to ten minutes of instrumental music", "选择没有歌词的音乐，专注感受旋律和乐器。", "Choose music without lyrics and focus on melody and instruments."),
    funCase(19, "比较同一首歌的两个版本", "Compare two versions of one song", "听原唱和翻唱，记录编曲或情绪上的差异。", "Listen to an original and a cover, noting differences in arrangement or mood."),
    funCase(20, "为今天选一首主题曲", "Choose a theme song for today", "选一首符合今天心情的歌，并写下选择原因。", "Pick a song that matches today's mood and write down why."),
    funCase(21, "看一部短片", "Watch a short film", "选择一部二十分钟以内的短片，完整看完故事。", "Choose a short film under twenty minutes and watch the whole story."),
    funCase(22, "重温一部喜欢的电影", "Rewatch a favorite film", "挑一部熟悉的电影，留意以前忽略的一个细节。", "Rewatch a familiar film and notice one detail you missed before."),
    funCase(23, "看一集没看过的纪录片", "Watch a new documentary episode", "选择感兴趣的主题，记录一个新了解到的事实。", "Choose an interesting topic and record one new fact."),
    funCase(24, "看一集经典电视剧", "Watch a classic television episode", "选择一部经典剧集，观察它的对白和节奏。", "Choose a classic episode and notice its dialogue and pacing."),
    funCase(25, "看一次电影幕后花絮", "Watch behind-the-scenes footage", "了解一个镜头、角色或场景是如何制作的。", "Learn how one shot, character, or scene was created."),
    funCase(26, "为一部电影写一句评价", "Write a one-line film review", "用一句话概括观感，不复述完整剧情。", "Summarize your reaction in one sentence without retelling the plot."),
    funCase(27, "看一段无对白表演", "Watch a performance without dialogue", "关注演员动作、表情和画面如何表达故事。", "Notice how movement, expression, and visuals communicate the story."),
    funCase(28, "找出一部电影的最佳镜头", "Choose the best shot in a film", "截取或描述最喜欢的画面，并说明理由。", "Capture or describe your favorite shot and explain why."),
    funCase(29, "看一部陌生国家的电影", "Watch a film from another country", "选择平时少接触的地区，感受不同叙事方式。", "Choose a region you rarely explore and notice its storytelling style."),
    funCase(30, "安排一个无手机观影时间", "Watch without using your phone", "观影期间把手机放远，完整关注画面和声音。", "Put your phone away and focus fully on the picture and sound."),
    funCase(31, "完成一个简单拼图", "Complete a simple puzzle", "选择块数较少的拼图，先从边缘开始整理。", "Choose a small puzzle and begin by sorting the edge pieces."),
    funCase(32, "玩一局纸牌游戏", "Play one card game", "选择熟悉的规则，和家人或朋友完成一局。", "Use familiar rules and finish one round with family or friends."),
    funCase(33, "玩一次猜词游戏", "Play a word-guessing game", "准备几个简单词语，轮流描述但不直接说出答案。", "Prepare simple words and take turns describing them without saying the answer."),
    funCase(34, "完成一个数独", "Complete a sudoku", "选择适合自己的难度，不计时完成一次。", "Choose a suitable difficulty and solve it without timing yourself."),
    funCase(35, "玩一次五子棋", "Play a game of gomoku", "和对手完成一局，并在结束后回看关键一步。", "Finish one match and review one important move afterward."),
    funCase(36, "搭一座积木小屋", "Build a small block house", "使用现有积木自由搭建，不按照固定图纸。", "Build freely with available blocks instead of following instructions."),
    funCase(37, "挑战一个迷宫", "Solve a maze", "找一张纸上迷宫，从入口走到出口。", "Find a paper maze and trace a path from entrance to exit."),
    funCase(38, "玩一次你画我猜", "Play a drawing-guessing game", "轮流画一个词，让其他人猜出答案。", "Take turns drawing a word for others to guess."),
    funCase(39, "设计一道选择题", "Create a trivia question", "围绕熟悉的主题设计一个问题和四个选项。", "Create one question and four choices about a familiar topic."),
    funCase(40, "尝试一款新桌游", "Try a new board game", "先学习基础规则，再完成一局入门体验。", "Learn the basic rules and complete one beginner round."),
    funCase(41, "读十页小说", "Read ten pages of a novel", "找一个安静位置，连续读完十页内容。", "Find a quiet place and read ten pages without interruption."),
    funCase(42, "读一首诗", "Read a poem", "慢慢读两遍，选出最有感觉的一句。", "Read it slowly twice and choose the line that affects you most."),
    funCase(43, "翻一本旧杂志", "Browse an old magazine", "随意翻阅，并找出一篇仍然有趣的内容。", "Browse freely and find one article that remains interesting."),
    funCase(44, "读一个漫画章节", "Read one comic chapter", "完整读完一个章节，留意最喜欢的画格。", "Finish one chapter and notice your favorite panel."),
    funCase(45, "为故事改一个结局", "Rewrite a story ending", "给熟悉的故事写一个不同但合理的短结局。", "Write a different but plausible short ending for a familiar story."),
    funCase(46, "摘抄一段喜欢的文字", "Copy a favorite passage", "手写一小段文字，并注明它来自哪里。", "Handwrite a short passage and note its source."),
    funCase(47, "给小说角色写一句话", "Write a note to a fictional character", "告诉角色你赞同或不理解他的哪次选择。", "Tell the character which choice you support or question."),
    funCase(48, "猜一本书的故事走向", "Predict what happens next in a book", "读到章节中间时停下，写下自己的预测。", "Pause midway through a chapter and write your prediction."),
    funCase(49, "整理一份想读书单", "Build a reading list", "选出五本真正想读的书，并标记先后顺序。", "Choose five books you genuinely want to read and rank them."),
    funCase(50, "和朋友交换一本书", "Exchange a book with a friend", "互相推荐一本书，并说明推荐的理由。", "Recommend one book to each other and explain why."),
    funCase(51, "画一只简单小动物", "Draw a simple animal", "用基本形状画出一只小动物，再补充表情。", "Use basic shapes to draw an animal and add an expression."),
    funCase(52, "给一幅线稿上色", "Color a line drawing", "选择三到五种颜色，完成一张小线稿。", "Choose three to five colors and complete a small line drawing."),
    funCase(53, "画一张窗外的景色", "Draw the view outside", "不用追求准确，只记录最明显的形状和颜色。", "Do not aim for accuracy; capture the strongest shapes and colors."),
    funCase(54, "设计一个简单图标", "Design a simple icon", "用尽量少的线条表达一个常见物品。", "Use as few lines as possible to represent a common object."),
    funCase(55, "临摹一幅小画", "Copy a small artwork", "选择结构简单的作品，观察比例和色彩。", "Choose a simple artwork and study its proportions and colors."),
    funCase(56, "用三种颜色画画", "Draw with only three colors", "限制颜色数量，用明暗和面积丰富画面。", "Limit the palette and use value and shape to enrich the image."),
    funCase(57, "画一张今天的心情", "Draw today's mood", "用颜色、线条或形状表达现在的感受。", "Use color, lines, or shapes to express how you feel."),
    funCase(58, "为房间画一张平面图", "Sketch a room floor plan", "从俯视角度画出家具的大致位置。", "Draw the approximate furniture positions from above."),
    funCase(59, "设计一张小贺卡", "Design a small greeting card", "确定主题并完成封面图案和一句祝福。", "Choose a theme and add a cover design and one greeting."),
    funCase(60, "完成一幅二十分钟速写", "Complete a twenty-minute sketch", "选择眼前物品，在限定时间内抓住主要结构。", "Choose a nearby object and capture its main structure within twenty minutes."),
    funCase(61, "拍一张对称构图", "Take a symmetrical photo", "寻找左右或上下较为对称的场景进行拍摄。", "Find a scene with horizontal or vertical symmetry and photograph it."),
    funCase(62, "拍一张影子照片", "Take a shadow photo", "利用阳光或灯光，记录一个有趣的影子。", "Use sunlight or a lamp to capture an interesting shadow."),
    funCase(63, "拍一种颜色", "Photograph one color", "在周围寻找同一种颜色的三个物品。", "Find and photograph three nearby objects sharing one color."),
    funCase(64, "拍一张低角度照片", "Take a low-angle photo", "从接近地面的位置拍摄熟悉的场景。", "Photograph a familiar scene from close to the ground."),
    funCase(65, "拍一张生活静物", "Photograph a still life", "挑选三件日常物品，简单摆放后拍摄。", "Arrange three everyday objects and photograph them."),
    funCase(66, "记录一次日落", "Capture a sunset", "在安全位置拍下光线变化最明显的时刻。", "From a safe location, capture the moment when the light changes most."),
    funCase(67, "拍一组手部动作", "Photograph hands at work", "记录写字、做饭或整理物品时的手部细节。", "Capture hands writing, cooking, or organizing something."),
    funCase(68, "用黑白模式拍三张照片", "Take three black-and-white photos", "关注光影、线条和纹理，而不是颜色。", "Focus on light, lines, and texture instead of color."),
    funCase(69, "拍一张框中框构图", "Take a frame-within-a-frame photo", "利用门窗或物体边缘包围主要画面。", "Use doors, windows, or object edges to frame the subject."),
    funCase(70, "完成一个九宫格摄影主题", "Create a nine-photo theme", "围绕一个简单主题拍摄九张相互呼应的照片。", "Take nine related photos around one simple theme."),
    funCase(71, "折一只纸鹤", "Fold a paper crane", "跟随步骤完成一只纸鹤，并调整翅膀形状。", "Follow the steps to fold a crane and shape its wings."),
    funCase(72, "做一个纸质书签", "Make a paper bookmark", "裁剪硬纸并添加简单图案或一句话。", "Cut sturdy paper and add a simple design or phrase."),
    funCase(73, "用旧包装做收纳盒", "Make a box from old packaging", "清理一个纸盒并重新装饰，用来收纳小物。", "Clean and decorate a small package to store little items."),
    funCase(74, "串一个简单手链", "Make a simple bracelet", "选择少量珠子或绳结，完成一条可佩戴手链。", "Use a few beads or knots to create a wearable bracelet."),
    funCase(75, "捏一个黏土小物", "Make a small clay figure", "用简单形状组合一个水果、动物或摆件。", "Combine basic shapes into a fruit, animal, or ornament."),
    funCase(76, "做一张拼贴画", "Make a collage", "剪取旧纸张上的图案，重新组合成一幅画面。", "Cut images from old paper and recombine them into one scene."),
    funCase(77, "装饰一个玻璃瓶", "Decorate a glass jar", "清洁空瓶后，用绳子、贴纸或纸张进行装饰。", "Clean an empty jar and decorate it with string, stickers, or paper."),
    funCase(78, "制作一个照片夹", "Make a photo holder", "用硬纸或铁丝制作能立住一张照片的小支架。", "Use card or wire to make a small stand for one photograph."),
    funCase(79, "缝补一个松开的纽扣", "Sew on a loose button", "选择合适线色，把纽扣牢固缝回原位。", "Choose matching thread and securely sew the button back on."),
    funCase(80, "完成一个一小时手工作品", "Complete a one-hour craft", "选择材料简单的小作品，从准备到收尾完整完成。", "Choose a simple craft and complete it from setup through cleanup."),
    funCase(81, "写一个六十字小故事", "Write a sixty-word story", "用有限篇幅写清人物、变化和结尾。", "Use a short format to establish a character, change, and ending."),
    funCase(82, "写四句小诗", "Write a four-line poem", "围绕今天看到的一个画面写四句话。", "Write four lines about one scene you noticed today."),
    funCase(83, "给普通物品起新名字", "Rename an ordinary object", "选择一个日常物品，为它设计一个有趣的新名字。", "Choose an everyday object and invent an amusing new name."),
    funCase(84, "设计一个虚构角色", "Design a fictional character", "写下角色的名字、特点和一个小秘密。", "Give the character a name, traits, and one small secret."),
    funCase(85, "为照片写一句台词", "Write a caption as dialogue", "挑一张照片，想象画面中的人物会说什么。", "Choose a photo and imagine what someone in it would say."),
    funCase(86, "编一个一分钟笑话", "Create a one-minute joke", "设计简单铺垫和意外结尾，讲给朋友听。", "Build a simple setup and surprise ending, then tell a friend."),
    funCase(87, "录一段一分钟短片", "Record a one-minute video", "围绕一个小主题完成开头、过程和结尾。", "Use one small theme with a beginning, middle, and end."),
    funCase(88, "为一天制作声音日记", "Create an audio diary", "录下三段代表今天不同时间的环境声音。", "Record three ambient sounds representing different parts of the day."),
    funCase(89, "设计一张虚构电影海报", "Design a fictional movie poster", "确定片名、类型和主视觉，完成简单草图。", "Choose a title, genre, and main visual, then sketch the poster."),
    funCase(90, "写一个三分钟广播稿", "Write a three-minute radio script", "围绕熟悉主题安排开场、内容和结束语。", "Structure an introduction, main content, and closing around a familiar topic."),
    funCase(91, "举办一次家庭电影夜", "Host a family movie night", "共同选择影片，准备简单零食并安排不被打扰的时间。", "Choose a film together, prepare snacks, and reserve uninterrupted time."),
    funCase(92, "组织一次小型桌游局", "Organize a small board-game session", "确定人数、游戏和时间，并提前说明基础规则。", "Set the group size, game, and time, and explain the basic rules."),
    funCase(93, "完成一次主题摄影散步", "Take a themed photo walk", "围绕门、数字或颜色等主题拍摄一组照片。", "Photograph a theme such as doors, numbers, or colors during a walk."),
    funCase(94, "制作一份年度歌单", "Create a yearly playlist", "选择代表不同阶段的歌曲，并按时间或情绪排列。", "Choose songs representing different periods and arrange them by time or mood."),
    funCase(95, "策划一次朋友才艺分享", "Plan a talent-sharing evening", "邀请朋友各准备一个短节目，控制整体时长。", "Invite friends to prepare short acts and keep the event to a clear length."),
    funCase(96, "创作一本八页小书", "Create an eight-page mini book", "用一张纸制作小书，并完成一个简单图文故事。", "Fold a mini book from one sheet and fill it with a simple illustrated story."),
    funCase(97, "拍摄一段完整短剧情", "Film a complete short scene", "准备简短脚本、镜头顺序和基础剪辑，讲完一个小故事。", "Use a short script, shot order, and basic editing to tell a complete story."),
    funCase(98, "举办一次作品展示", "Hold a small creative showcase", "挑选近期作品，整理展示顺序并邀请朋友观看。", "Select recent work, arrange it, and invite friends to view it."),
    funCase(99, "设计一个周末娱乐计划", "Design a weekend entertainment plan", "组合一项户外活动、一项室内活动和充足休息。", "Combine one outdoor activity, one indoor activity, and enough rest."),
    funCase(100, "完成一次七天创作挑战", "Complete a seven-day creative challenge", "连续七天每天完成一个小作品，最后整理成合集。", "Create one small work each day for seven days and collect them at the end."),
)

private fun funCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-fun-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_fun,
    imageAsset = "fun",
)
