package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun homeRecommendationCases(): List<RecommendationCase> = listOf(
    homeCase(1, "整理一个小角落", "Tidy one small corner", "选择桌边或墙角，用五分钟收起明显杂物。", "Choose a desk edge or corner and put away visible clutter for five minutes."),
    homeCase(2, "擦干净一张桌子", "Wipe one table clean", "移开桌面物品，擦净灰尘和污渍后再整齐放回。", "Clear the surface, wipe away dust and marks, then return items neatly."),
    homeCase(3, "收好散落的衣物", "Put away loose clothes", "把衣物分成待洗、可继续穿和需要收纳三类。", "Sort clothes into laundry, rewear, and storage groups."),
    homeCase(4, "倒掉一次垃圾", "Take out the trash", "检查垃圾袋是否需要更换，并把新袋固定好。", "Check whether the liner needs replacing and secure a fresh one."),
    homeCase(5, "给房间通风十分钟", "Air out a room for ten minutes", "在天气和安全允许时打开窗户，让空气流通。", "When weather and safety allow, open a window for fresh air."),
    homeCase(6, "把鞋子摆整齐", "Arrange your shoes", "将常穿鞋靠外摆放，其余鞋子清洁后收好。", "Keep frequently worn shoes accessible and store the rest after cleaning."),
    homeCase(7, "整理沙发上的物品", "Clear items from the sofa", "把衣物、书和遥控器分别放回固定位置。", "Return clothes, books, and remotes to their designated places."),
    homeCase(8, "洗好今天的杯子", "Wash today's cups", "清洗杯身和杯口，并倒扣晾干。", "Wash the body and rim, then leave the cups upside down to dry."),
    homeCase(9, "扫一遍门口", "Sweep the entryway", "清除门口的灰尘、头发和小颗粒。", "Remove dust, hair, and small debris from the entryway."),
    homeCase(10, "把遥控器放回原位", "Return remotes to their place", "收齐常用遥控器，并设置一个固定存放位置。", "Gather common remotes and give them one permanent storage spot."),
    homeCase(11, "整理一个抽屉", "Organize one drawer", "取出全部物品，留下需要的东西并分类放回。", "Empty the drawer, keep what is needed, and return items by category."),
    homeCase(12, "整理一层书架", "Organize one bookshelf", "把书立好，并移走不属于这一层的物品。", "Stand books upright and remove anything that belongs elsewhere."),
    homeCase(13, "清理床头柜", "Clear the bedside table", "只保留睡前会用到的物品，擦净桌面。", "Keep only bedtime essentials and wipe the surface clean."),
    homeCase(14, "整理一个收纳盒", "Organize one storage box", "检查盒内物品，把同类物件集中放置。", "Review the contents and group similar items together."),
    homeCase(15, "清空一个购物袋", "Empty one shopping bag", "把袋中物品归位，并将袋子折好或回收。", "Put away the contents and fold or recycle the bag."),
    homeCase(16, "整理一小叠文件", "Sort a small stack of papers", "区分保留、处理和回收，避免文件继续堆积。", "Separate papers into keep, action, and recycle groups."),
    homeCase(17, "收好充电线", "Organize charging cables", "卷好常用线材，并放进固定的小盒或抽屉。", "Coil common cables and place them in a designated box or drawer."),
    homeCase(18, "整理常用药品", "Organize common medicines", "检查名称和日期，将药品放在安全干燥的位置。", "Check labels and dates, then store medicines in a safe dry place."),
    homeCase(19, "处理三件闲置物品", "Process three unused items", "分别决定保留、捐赠、转卖或回收。", "Decide whether to keep, donate, sell, or recycle each item."),
    homeCase(20, "给物品设置固定位置", "Assign one item a permanent place", "选择一件经常找不到的东西，为它确定存放点。", "Choose an often-misplaced item and give it a fixed home."),
    homeCase(21, "擦一次客厅地面", "Mop the living room floor", "先清除杂物和灰尘，再从房间内部向门口清洁。", "Remove clutter and dust first, then mop from the far side toward the door."),
    homeCase(22, "清洁一次卧室地面", "Clean the bedroom floor", "移动轻便物品，清理床边和容易积灰的位置。", "Move light items and clean beside the bed and other dusty areas."),
    homeCase(23, "擦一遍窗台", "Wipe the windowsill", "清除灰尘，并检查是否有积水或杂物。", "Remove dust and check for standing water or clutter."),
    homeCase(24, "清洁一面镜子", "Clean one mirror", "使用合适工具擦去水渍和指纹，不留下明显条纹。", "Use suitable tools to remove marks and fingerprints without streaks."),
    homeCase(25, "擦拭门把手", "Wipe door handles", "清洁家中几个高频接触的门把手。", "Clean several frequently touched door handles."),
    homeCase(26, "清洁灯开关", "Clean light switches", "断开相关电源风险并用微湿工具轻轻擦拭表面。", "Avoid electrical risk and wipe the surface gently with a barely damp tool."),
    homeCase(27, "掸去家具表面灰尘", "Dust furniture surfaces", "从较高位置开始，依次清理到较低位置。", "Begin with higher surfaces and work downward."),
    homeCase(28, "清洁踢脚线一段", "Clean one section of baseboard", "用布擦净一小段容易忽略的踢脚线。", "Wipe one often-overlooked section of baseboard."),
    homeCase(29, "清理沙发缝隙", "Clean sofa crevices", "取出掉落物，再吸除缝隙中的灰尘和碎屑。", "Remove fallen objects, then vacuum dust and crumbs from the gaps."),
    homeCase(30, "完成一次客厅除尘", "Dust the living room", "按从上到下的顺序清洁主要表面和角落。", "Clean major surfaces and corners from top to bottom."),
    homeCase(31, "清洗今天的碗筷", "Wash today's dishes", "清除残渣，洗净后放到通风位置沥干。", "Remove food residue, wash thoroughly, and leave items to drain."),
    homeCase(32, "擦干净厨房台面", "Wipe the kitchen counter", "收起食材和工具，再清理油渍与水渍。", "Put away ingredients and tools, then remove grease and water marks."),
    homeCase(33, "清洁一次灶台", "Clean the stovetop", "确认灶台冷却后，擦去食物残渣和油污。", "Wait until the stovetop is cool, then remove food and grease."),
    homeCase(34, "清洗水槽", "Clean the sink", "清除滤网残渣，刷洗水槽并冲净清洁剂。", "Empty the strainer, scrub the sink, and rinse away cleaner."),
    homeCase(35, "整理一层冰箱", "Organize one refrigerator shelf", "取出过期物品，擦净层板后按类别放回。", "Remove expired items, wipe the shelf, and return food by category."),
    homeCase(36, "检查三样食品日期", "Check three food dates", "优先查看开封或容易变质的食物。", "Focus on opened foods and items that spoil quickly."),
    homeCase(37, "清理一次微波炉", "Clean the microwave", "在断电或安全状态下擦净内部食物飞溅。", "With the appliance safely off, wipe food splashes from the interior."),
    homeCase(38, "清洗一块厨房抹布", "Wash a kitchen cloth", "使用合适方式彻底清洗，并展开晾干。", "Wash it thoroughly using an appropriate method and hang it open to dry."),
    homeCase(39, "整理调味料", "Organize seasonings", "检查瓶盖和日期，把常用调料放在顺手位置。", "Check lids and dates, then place common seasonings within easy reach."),
    homeCase(40, "完成一次厨房清洁", "Complete a kitchen cleanup", "依次处理碗筷、台面、水槽、灶台和地面。", "Handle dishes, counter, sink, stovetop, and floor in sequence."),
    homeCase(41, "更换一条干净毛巾", "Replace a towel", "取下使用中的毛巾，换上干燥清洁的一条。", "Remove the used towel and replace it with a clean dry one."),
    homeCase(42, "清洗一批日常衣物", "Wash a load of everyday clothes", "按颜色和材质简单分类，再选择合适程序。", "Sort roughly by color and fabric before choosing a suitable cycle."),
    homeCase(43, "晾好一批衣物", "Hang a load of laundry", "抖开衣物并留出间隔，让空气能够流通。", "Shake out each item and leave space for air to circulate."),
    homeCase(44, "收下一批干衣服", "Bring in dry laundry", "确认完全干燥后收下，并及时折叠或悬挂。", "Make sure everything is dry, then fold or hang it promptly."),
    homeCase(45, "折好十件衣物", "Fold ten clothing items", "按类别折叠并放回对应抽屉或衣柜。", "Fold by category and return each item to the correct drawer or closet."),
    homeCase(46, "清洗一套床上用品", "Wash one set of bedding", "按照洗涤标签处理床单、被套和枕套。", "Follow care labels for the sheet, duvet cover, and pillowcases."),
    homeCase(47, "更换床单", "Change the bedsheet", "取下旧床单，清理床面后铺上干净床单。", "Remove the used sheet, clear the mattress surface, and fit a clean one."),
    homeCase(48, "整理衣柜的一层", "Organize one wardrobe shelf", "把当季衣物放在方便拿取的位置。", "Place current-season clothing where it is easy to reach."),
    homeCase(49, "检查衣物口袋", "Check clothing pockets", "洗衣前取出纸巾、票据和其他小物。", "Remove tissues, receipts, and small objects before washing."),
    homeCase(50, "处理一件需要修补的衣服", "Handle one item needing repair", "缝补、送修或放入明确的待处理区域。", "Repair it, send it out, or place it in a clear action area."),
    homeCase(51, "清洁洗手台", "Clean the bathroom sink", "移开瓶罐，擦净水垢、皂渍和台面积水。", "Move bottles aside and remove scale, soap marks, and standing water."),
    homeCase(52, "刷洗一次马桶", "Clean the toilet", "使用专用工具清洁，并注意手部和环境卫生。", "Use dedicated tools and maintain proper hand and area hygiene."),
    homeCase(53, "擦干浴室地面", "Dry the bathroom floor", "清除积水，保持通道干燥以减少滑倒风险。", "Remove standing water and keep the walking area dry."),
    homeCase(54, "整理洗漱用品", "Organize toiletries", "丢弃空瓶，将每天使用的用品集中摆放。", "Discard empty containers and group daily-use products together."),
    homeCase(55, "清洗牙刷杯", "Wash the toothbrush cup", "倒掉积水，刷洗杯底和杯壁后晾干。", "Empty standing water, wash the base and sides, and let it dry."),
    homeCase(56, "擦拭淋浴区水渍", "Wipe shower water marks", "使用合适工具清理玻璃或墙面的水渍。", "Use a suitable tool to remove water marks from glass or walls."),
    homeCase(57, "清理地漏表面", "Clear the drain cover", "戴好手套，移除表面头发和可见杂物。", "Wear gloves and remove hair and visible debris from the cover."),
    homeCase(58, "更换浴室垃圾袋", "Replace the bathroom bin liner", "清空垃圾桶，必要时擦净内部再套上新袋。", "Empty the bin, wipe the inside if needed, and add a fresh liner."),
    homeCase(59, "给浴室通风", "Ventilate the bathroom", "洗浴后打开排风或窗户，帮助湿气散去。", "Use the fan or window after bathing to reduce moisture."),
    homeCase(60, "完成一次浴室清洁", "Complete a bathroom cleanup", "按洗手台、马桶、淋浴区和地面的顺序处理。", "Clean the sink, toilet, shower area, and floor in sequence."),
    homeCase(61, "给植物浇一次水", "Water the plants", "先检查土壤，只给真正需要的植物补水。", "Check the soil first and water only plants that need it."),
    homeCase(62, "擦拭植物叶片", "Wipe plant leaves", "用柔软湿布轻轻清除较大叶片上的灰尘。", "Use a soft damp cloth to remove dust from larger leaves."),
    homeCase(63, "清理一个花盆托盘", "Clean one plant saucer", "倒掉积水并擦净泥土，避免长期潮湿。", "Empty standing water and wipe away soil to prevent lingering moisture."),
    homeCase(64, "检查家中灯泡", "Check household light bulbs", "记录不亮或闪烁的灯泡，准备合适替换品。", "Note bulbs that are out or flickering and prepare suitable replacements."),
    homeCase(65, "给松动螺丝加固", "Tighten one loose screw", "使用合适工具处理一个简单且安全的松动位置。", "Use the correct tool on one simple, safe loose fitting."),
    homeCase(66, "检查门窗是否顺畅", "Check a door or window", "开合一次，记录卡顿、异响或密封问题。", "Open and close it once and note sticking, noise, or sealing issues."),
    homeCase(67, "更换一个耗尽电池", "Replace one dead battery", "确认电池型号和方向，并妥善回收旧电池。", "Confirm the battery type and direction, then recycle the old one properly."),
    homeCase(68, "清洁一个风扇外罩", "Clean one fan guard", "断电后清除外罩灰尘，不拆卸不熟悉的部件。", "Unplug it and remove surface dust without dismantling unfamiliar parts."),
    homeCase(69, "检查一次烟雾报警器", "Check a smoke alarm", "按设备说明测试，并记录需要更换电池的情况。", "Test it according to its instructions and note if the battery needs replacing."),
    homeCase(70, "列一份家庭维修清单", "Make a home repair list", "记录需要处理的问题、优先级和适合的解决方式。", "List issues, priorities, and the appropriate way to resolve each one."),
    homeCase(71, "整理玄关", "Organize the entryway", "收好鞋包、钥匙和雨具，保持进出通道畅通。", "Store shoes, bags, keys, and umbrellas while keeping the path clear."),
    homeCase(72, "整理餐桌", "Clear the dining table", "移走非用餐物品，擦净桌面并摆好常用物件。", "Remove non-dining items, wipe the table, and arrange essentials."),
    homeCase(73, "整理卧室", "Tidy the bedroom", "铺好床铺、收起衣物，并清理主要表面。", "Make the bed, put away clothes, and clear main surfaces."),
    homeCase(74, "整理客厅", "Tidy the living room", "归位沙发、茶几和地面上的常用物品。", "Return common items from the sofa, table, and floor to their places."),
    homeCase(75, "整理阳台", "Tidy the balcony", "移除杂物，检查排水口并保持通道安全。", "Remove clutter, check the drain, and keep the walkway safe."),
    homeCase(76, "整理书房", "Tidy the study", "归档文件、收好文具并清理桌面。", "File papers, store stationery, and clear the desk."),
    homeCase(77, "整理储物间一角", "Organize one storage-room corner", "先处理能看清的小范围，不一次搬动过多物品。", "Work on one visible area without moving too many items at once."),
    homeCase(78, "清理床底空间", "Clear the space under the bed", "取出杂物和灰尘，只放回适合长期收纳的东西。", "Remove clutter and dust, returning only items suitable for storage."),
    homeCase(79, "整理儿童活动区", "Tidy a children's activity area", "按玩具、图书和绘画用品分类，并确保通道安全。", "Sort toys, books, and art supplies while keeping paths safe."),
    homeCase(80, "完成一个房间的复位", "Reset one room", "让物品归位、表面整洁、垃圾清空并保持通风。", "Return items, clear surfaces, empty trash, and refresh the air."),
    homeCase(81, "清点清洁用品", "Inventory cleaning supplies", "检查余量和有效状态，避免重复购买。", "Check quantities and condition to avoid unnecessary purchases."),
    homeCase(82, "补充一种日常用品", "Restock one household essential", "确认库存不足后，补充纸巾、清洁剂或垃圾袋。", "After confirming low stock, replace tissues, cleaner, or bin liners."),
    homeCase(83, "整理一周家务清单", "Create a weekly chore list", "按房间和频率列出本周需要完成的事项。", "List this week's chores by room and frequency."),
    homeCase(84, "给家务安排十分钟", "Schedule ten minutes for chores", "选择一个明确任务，在计时结束后停止。", "Choose one clear task and stop when the timer ends."),
    homeCase(85, "分配一次家庭家务", "Assign household chores", "根据时间和能力明确每个人负责的事项。", "Assign tasks according to each person's time and ability."),
    homeCase(86, "检查家庭消耗品库存", "Check household consumables", "查看纸品、洗护和清洁用品还能使用多久。", "Estimate how long paper, personal care, and cleaning supplies will last."),
    homeCase(87, "准备一套来客用品", "Prepare a guest set", "整理干净毛巾、拖鞋和备用洗漱用品。", "Set aside clean towels, slippers, and spare toiletries."),
    homeCase(88, "记录一个家务耗时", "Time one household task", "记录实际用时，帮助以后更合理地安排。", "Track the actual duration to plan future chores more realistically."),
    homeCase(89, "完成一次周末家务复盘", "Review weekend chores", "确认已完成事项，并把未完成内容重新安排。", "Confirm what was completed and reschedule anything unfinished."),
    homeCase(90, "制定一个月用品采购单", "Create a monthly supply list", "根据库存和使用速度列出真正需要购买的物品。", "Base the list on current stock and actual usage rates."),
    homeCase(91, "完成一次全屋除尘", "Dust the entire home", "按房间从高到低清洁，并最后处理地面。", "Work room by room from high to low and finish with the floors."),
    homeCase(92, "完成一次全屋地面清洁", "Clean all household floors", "先吸尘或扫地，再根据材质选择合适清洁方式。", "Vacuum or sweep first, then use a method suitable for each floor."),
    homeCase(93, "整理一次整个衣柜", "Organize the whole wardrobe", "按季节和类别整理，并处理不再需要的衣物。", "Sort by season and category and process clothing no longer needed."),
    homeCase(94, "完成一次冰箱深度整理", "Deep-organize the refrigerator", "清空分区、检查日期、擦洗内部并合理放回食物。", "Empty sections, check dates, clean inside, and return food logically."),
    homeCase(95, "完成一次厨房深度清洁", "Deep-clean the kitchen", "安排灶台、油烟区域、柜门、冰箱和地面的清洁顺序。", "Plan the order for the stovetop, greasy areas, cabinets, refrigerator, and floor."),
    homeCase(96, "完成一次浴室深度清洁", "Deep-clean the bathroom", "处理水垢、缝隙、排水和通风，并全程注意安全。", "Address scale, gaps, drainage, and ventilation while working safely."),
    homeCase(97, "重新规划一个收纳区域", "Redesign one storage area", "根据使用频率调整位置，并为类别增加清楚标签。", "Rearrange by usage frequency and add clear category labels."),
    homeCase(98, "进行一次家庭安全检查", "Complete a household safety check", "查看通道、插座、燃气、报警器和紧急用品。", "Review pathways, outlets, gas, alarms, and emergency supplies."),
    homeCase(99, "制定一套季度家务计划", "Create a quarterly chore plan", "安排日常、每周、每月和换季任务，避免集中处理。", "Schedule daily, weekly, monthly, and seasonal tasks to spread the work."),
    homeCase(100, "完成一次全屋整理日", "Complete a whole-home reset day", "提前分区和分工，依次完成取舍、归位、清洁和收尾。", "Plan zones and roles, then declutter, organize, clean, and finish each area."),
)

private fun homeCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-home-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_home,
    imageAsset = "home",
)
