package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun relaxRecommendationCases(): List<RecommendationCase> = listOf(
    relaxCase(1, "闭眼休息一分钟", "Rest your eyes for one minute", "放下手里的事情，闭上眼睛并让面部肌肉放松。", "Pause what you are doing, close your eyes, and relax your facial muscles."),
    relaxCase(2, "缓慢深呼吸五次", "Take five slow breaths", "用鼻子吸气、缓慢呼气，不需要刻意吸得很深。", "Breathe in through your nose and exhale slowly without forcing a deep breath."),
    relaxCase(3, "喝一杯温水", "Drink a glass of warm water", "小口喝完一杯温水，感受身体慢慢安静下来。", "Sip a glass of warm water and let your body settle."),
    relaxCase(4, "看看窗外的天空", "Look at the sky outside", "暂时离开屏幕，观察天空的颜色和云层。", "Step away from the screen and notice the sky's color and clouds."),
    relaxCase(5, "伸一个懒腰", "Take a full-body stretch", "缓慢抬高手臂并伸展身体，不要突然用力。", "Raise your arms slowly and stretch without forcing the movement."),
    relaxCase(6, "安静坐两分钟", "Sit quietly for two minutes", "不处理消息，也不安排下一件事，只保持自然呼吸。", "Do not check messages or plan the next task; simply breathe naturally."),
    relaxCase(7, "放松下巴和肩膀", "Relax your jaw and shoulders", "松开咬紧的牙齿，让肩膀自然向下沉。", "Unclench your teeth and allow your shoulders to drop naturally."),
    relaxCase(8, "听一首轻音乐", "Listen to one gentle song", "选择节奏舒缓的音乐，完整听完后再继续做事。", "Choose a calming song and listen to it fully before continuing."),
    relaxCase(9, "慢慢洗一次手", "Wash your hands slowly", "感受水温和动作，把这段时间当作短暂停顿。", "Notice the water temperature and movement, using the moment as a brief pause."),
    relaxCase(10, "闻一闻喜欢的香气", "Enjoy a pleasant scent", "选择茶叶、咖啡或其他温和香气，轻轻闻几次。", "Choose tea, coffee, or another gentle scent and breathe it in lightly."),
    relaxCase(11, "做一分钟腹式呼吸", "Practice one minute of belly breathing", "把手放在腹部，观察吸气和呼气时的起伏。", "Place a hand on your abdomen and notice it rise and fall."),
    relaxCase(12, "延长五次呼气", "Lengthen five exhales", "让每次呼气比吸气稍长，保持过程轻松。", "Let each exhale last slightly longer than the inhale while staying comfortable."),
    relaxCase(13, "数十次自然呼吸", "Count ten natural breaths", "从一数到十，走神后只需温和地重新开始。", "Count from one to ten and gently restart if your attention wanders."),
    relaxCase(14, "跟随方形呼吸两分钟", "Try two minutes of box breathing", "用相同时间完成吸气、停顿、呼气和停顿。", "Use equal counts for inhaling, holding, exhaling, and pausing."),
    relaxCase(15, "对着手掌缓慢呼气", "Exhale slowly onto your palm", "感受气流的温度，连续完成五次缓慢呼气。", "Notice the warmth of the air and complete five slow exhales."),
    relaxCase(16, "做三次叹息式呼吸", "Take three physiological sighs", "短吸两次后缓慢长呼气，全程不要憋得不舒服。", "Take two short inhales followed by a long exhale without straining."),
    relaxCase(17, "用呼吸放松胸口", "Use breathing to relax your chest", "保持上身舒展，进行一分钟均匀呼吸。", "Keep your upper body open and breathe evenly for one minute."),
    relaxCase(18, "呼吸时默念平静", "Repeat a calming word while breathing", "吸气和呼气时默念一个让你安心的词。", "Silently repeat a reassuring word as you inhale and exhale."),
    relaxCase(19, "做五分钟呼吸练习", "Practice breathing for five minutes", "找一个舒服姿势，将注意力轻轻放在呼吸上。", "Find a comfortable position and rest your attention gently on your breath."),
    relaxCase(20, "记录呼吸后的感受", "Note how breathing changed you", "用一句话写下练习前后身体或情绪的变化。", "Write one sentence about any physical or emotional change."),
    relaxCase(21, "听十分钟轻音乐", "Listen to ten minutes of soft music", "降低音量，让音乐成为安静的背景。", "Keep the volume low and let the music form a quiet background."),
    relaxCase(22, "听一段自然声音", "Listen to nature sounds", "选择雨声、海浪或树林声音，专心听五分钟。", "Choose rain, waves, or forest sounds and listen for five minutes."),
    relaxCase(23, "听一首钢琴曲", "Listen to a piano piece", "闭眼听完一首钢琴曲，留意旋律的起伏。", "Close your eyes and notice how the melody rises and falls."),
    relaxCase(24, "听一段白噪音", "Listen to white noise", "用较低音量播放一小段，观察它是否帮助你安静。", "Play it softly for a short time and notice whether it helps you settle."),
    relaxCase(25, "听一场雨的声音", "Listen to the sound of rain", "如果正在下雨，就在安全室内安静听一会儿。", "If it is raining, listen quietly from a safe indoor place."),
    relaxCase(26, "听一段舒缓播客", "Listen to a calming podcast", "选择语速平稳的内容，听十分钟后暂停。", "Choose a gently paced episode and pause after ten minutes."),
    relaxCase(27, "整理一份放松歌单", "Create a relaxation playlist", "选出五首能让你慢下来的音乐。", "Choose five songs that help you slow down."),
    relaxCase(28, "用耳机听一次环境声", "Listen closely to ambient sound", "保持安全音量，分辨远近不同的声音。", "Keep the volume safe and distinguish sounds at different distances."),
    relaxCase(29, "关掉声音安静五分钟", "Spend five minutes in silence", "关闭媒体和通知，体验一段没有额外声音的时间。", "Turn off media and notifications for a period without added sound."),
    relaxCase(30, "记录最让你放松的声音", "Record your most relaxing sound", "写下今天最能让你安静的一种声音及原因。", "Write down which sound calmed you most today and why."),
    relaxCase(31, "用温水洗脸", "Wash your face with warm water", "让动作放慢，留意水温和皮肤的感觉。", "Slow down and notice the water temperature and sensation on your skin."),
    relaxCase(32, "泡脚十分钟", "Soak your feet for ten minutes", "使用舒适水温，坐稳后让双脚充分放松。", "Use a comfortable temperature and sit securely while your feet relax."),
    relaxCase(33, "洗一个温热的澡", "Take a warm shower", "控制合适水温，让肩颈在水流下慢慢放松。", "Use a comfortable temperature and let your neck and shoulders soften."),
    relaxCase(34, "热敷肩颈五分钟", "Warm your neck and shoulders", "使用温度安全的热毛巾，避免直接高温接触皮肤。", "Use a safely warm towel and avoid excessive heat on your skin."),
    relaxCase(35, "轻轻按摩太阳穴", "Gently massage your temples", "用指腹缓慢画圈一分钟，不要过度按压。", "Use your fingertips in slow circles for one minute without pressing hard."),
    relaxCase(36, "按摩双手两分钟", "Massage your hands for two minutes", "从掌心到手指逐一轻揉，放松长时间使用的双手。", "Gently rub from palms to fingers to relax overused hands."),
    relaxCase(37, "放松双脚三分钟", "Relax your feet for three minutes", "脱下鞋袜，轻轻活动脚趾并转动脚踝。", "Remove your shoes, wiggle your toes, and rotate your ankles gently."),
    relaxCase(38, "平躺休息十分钟", "Lie down for ten minutes", "选择支撑舒适的位置，不看手机，让身体安静休息。", "Choose a supported position, avoid your phone, and let your body rest."),
    relaxCase(39, "做一次身体扫描", "Do a body scan", "从头到脚观察紧张位置，不急着改变它。", "Notice areas of tension from head to toe without trying to change them."),
    relaxCase(40, "渐进放松五组肌肉", "Relax five muscle groups progressively", "依次轻轻绷紧并放松手、肩、脸、腿和脚。", "Gently tense and release your hands, shoulders, face, legs, and feet."),
    relaxCase(41, "暂时离开屏幕五分钟", "Take a five-minute screen break", "看向远处并活动身体，让眼睛和注意力休息。", "Look into the distance and move gently to rest your eyes and attention."),
    relaxCase(42, "关闭通知十分钟", "Mute notifications for ten minutes", "给自己一段不会被新消息打断的时间。", "Give yourself a short period without interruption from new messages."),
    relaxCase(43, "把手机放到另一个房间", "Leave your phone in another room", "在安全可行时离开手机十五分钟，做一件安静的小事。", "When practical, spend fifteen minutes away from your phone doing something quiet."),
    relaxCase(44, "停止刷新消息", "Stop refreshing messages", "关闭聊天和资讯页面，等到固定时间再查看。", "Close chat and news pages and check them at a planned time."),
    relaxCase(45, "清理手机主屏幕", "Simplify your phone home screen", "移走一个容易让你分心的应用入口。", "Remove one app shortcut that frequently distracts you."),
    relaxCase(46, "调低屏幕亮度", "Lower your screen brightness", "根据环境调整到舒适亮度，避免眼睛持续紧张。", "Set a comfortable brightness for the room to reduce eye strain."),
    relaxCase(47, "睡前半小时不刷短视频", "Avoid short videos before bed", "把睡前最后半小时留给更安静的活动。", "Reserve the final half hour before sleep for quieter activities."),
    relaxCase(48, "安排一个无屏幕午休", "Take a screen-free lunch break", "吃饭和休息时暂时不看电脑或手机。", "Avoid computers and phones while eating and resting."),
    relaxCase(49, "完成一次十五分钟数字休息", "Take a fifteen-minute digital break", "关闭所有屏幕，散步、喝水或安静坐着。", "Turn off all screens and walk, drink water, or sit quietly."),
    relaxCase(50, "记录屏幕休息后的变化", "Note the effect of a screen break", "写下眼睛、肩颈或心情是否发生变化。", "Note whether your eyes, neck, shoulders, or mood changed."),
    relaxCase(51, "晒五分钟太阳", "Sit in sunlight for five minutes", "在光线温和时到安全位置感受自然光。", "When the light is gentle, spend a few minutes safely in natural sunlight."),
    relaxCase(52, "在树下坐一会儿", "Sit under a tree", "选择安全干净的位置，观察树叶和光影。", "Choose a safe, clean place and notice the leaves and shifting light."),
    relaxCase(53, "慢慢走一圈", "Take one slow lap", "不追求步数和速度，只感受脚步与周围环境。", "Ignore steps and speed and simply notice your movement and surroundings."),
    relaxCase(54, "观察一片树叶", "Observe one leaf", "看看它的颜色、纹理和边缘，用一分钟专心观察。", "Spend one minute noticing its color, texture, and edges."),
    relaxCase(55, "听五分钟鸟鸣", "Listen for birds for five minutes", "在安全环境中分辨不同方向传来的声音。", "In a safe place, notice bird sounds coming from different directions."),
    relaxCase(56, "闻一闻雨后的空气", "Notice the air after rain", "站在避雨处，感受空气的温度和气味。", "Stand under shelter and notice the air's temperature and scent."),
    relaxCase(57, "看一次日落", "Watch a sunset", "提前找到安全位置，安静观察光线慢慢变化。", "Find a safe place and quietly watch the light change."),
    relaxCase(58, "照顾一盆植物", "Care for a plant", "检查土壤和叶片，只在需要时浇水或清理。", "Check the soil and leaves, watering or cleaning only if needed."),
    relaxCase(59, "在公园安静坐十分钟", "Sit quietly in a park for ten minutes", "选择舒适位置，不安排任务，只观察周围。", "Choose a comfortable place and simply observe without planning tasks."),
    relaxCase(60, "完成一次二十分钟自然散步", "Take a twenty-minute nature walk", "选择绿植较多的路线，保持轻松速度行走。", "Choose a greener route and walk at an easy pace."),
    relaxCase(61, "写下一件值得开心的小事", "Write down one small joy", "记录今天真实发生的一件微小好事。", "Record one small positive thing that genuinely happened today."),
    relaxCase(62, "写下一件可以放下的事", "Write down one thing to release", "把暂时无法解决的问题写下，并允许自己稍后再处理。", "Write down something you cannot solve now and allow yourself to return later."),
    relaxCase(63, "给自己写一句鼓励", "Write yourself one encouraging sentence", "像对待朋友一样，用温和语言回应当前的自己。", "Respond to yourself with the same kindness you would offer a friend."),
    relaxCase(64, "列出三件感谢的事", "List three things you appreciate", "可以是人物、经历或非常普通的生活细节。", "They can be people, experiences, or very ordinary details."),
    relaxCase(65, "写一页自由日记", "Write one page freely", "不修改也不评判，把脑中的想法连续写下来。", "Write continuously without editing or judging what appears."),
    relaxCase(66, "记录现在的情绪", "Name your current emotion", "选一个尽量准确的词，并写下它可能来自哪里。", "Choose the most accurate word you can and note what may have caused it."),
    relaxCase(67, "写下明天再处理的事情", "List what can wait until tomorrow", "把非紧急事项移出脑海，集中记录在一个位置。", "Move nonurgent concerns out of your mind and into one list."),
    relaxCase(68, "回忆一个安心的地方", "Recall a safe and peaceful place", "写下那个地方的声音、颜色和气味。", "Describe the sounds, colors, and scents of that place."),
    relaxCase(69, "写一封不发送的信", "Write a letter you will not send", "自由表达想说的话，写完后自行决定是否保留。", "Express what you need to say and decide afterward whether to keep it."),
    relaxCase(70, "完成十分钟情绪整理", "Spend ten minutes processing emotions", "写下发生了什么、你的感受和此刻真正需要什么。", "Write what happened, how you feel, and what you truly need now."),
    relaxCase(71, "睡前整理枕头和被子", "Prepare your pillow and bedding", "让睡眠空间保持整洁、舒适并适合休息。", "Make your sleeping space tidy, comfortable, and ready for rest."),
    relaxCase(72, "睡前调暗房间灯光", "Dim the lights before bed", "在准备睡觉前降低光线，让身体逐渐进入夜间状态。", "Lower the light before bed so your body can transition toward nighttime."),
    relaxCase(73, "睡前读五页书", "Read five pages before bed", "选择内容轻松的纸质书，读完后就停止。", "Choose a gentle paper book and stop after five pages."),
    relaxCase(74, "睡前听十分钟轻音乐", "Listen to soft music before bed", "设置自动停止，避免音乐整夜持续播放。", "Use a sleep timer so the music does not continue all night."),
    relaxCase(75, "把明早用品准备好", "Prepare tomorrow morning's essentials", "提前放好衣物和随身物品，减少睡前担忧。", "Set out clothes and essentials to reduce bedtime worry."),
    relaxCase(76, "睡前做三分钟拉伸", "Stretch gently for three minutes before bed", "选择舒缓动作，不进行剧烈或疼痛的拉伸。", "Use gentle movements and avoid intense or painful stretching."),
    relaxCase(77, "设置固定上床时间", "Set a regular bedtime", "选择现实可行的时间，并提前十分钟开始准备。", "Choose a realistic bedtime and begin preparing ten minutes earlier."),
    relaxCase(78, "睡前给房间通风", "Air out the bedroom", "在安全和天气允许时通风几分钟，再关好门窗。", "When safe and weather permits, air the room briefly before closing it."),
    relaxCase(79, "完成一次无手机睡前流程", "Complete a phone-free bedtime routine", "洗漱后不再查看手机，直接进行安静活动和休息。", "After washing up, avoid the phone and move into quiet activity and rest."),
    relaxCase(80, "设计一套二十分钟睡前流程", "Design a twenty-minute bedtime routine", "组合洗漱、整理、阅读或呼吸，并保持步骤简单。", "Combine washing, tidying, reading, or breathing into a simple sequence."),
    relaxCase(81, "泡一杯不含咖啡因的热饮", "Make a caffeine-free warm drink", "选择适合自己的饮品，小口喝完并留意温度。", "Choose a suitable drink, sip slowly, and mind the temperature."),
    relaxCase(82, "整理一个安静角落", "Create a quiet corner", "清理一小块空间，放上坐垫、书或柔和灯光。", "Clear a small space and add a cushion, book, or soft light."),
    relaxCase(83, "点亮一盏柔和小灯", "Turn on a soft lamp", "关闭刺眼主灯，用较温和的光线休息一会儿。", "Switch off harsh overhead light and rest under softer lighting."),
    relaxCase(84, "慢慢喝一杯茶", "Drink a cup of tea slowly", "选择低咖啡因或无咖啡因茶，留意香气和温度。", "Choose low- or no-caffeine tea and notice its aroma and warmth."),
    relaxCase(85, "整理一份舒适衣物", "Prepare comfortable clothing", "换上宽松干净的衣物，让身体减少束缚感。", "Change into clean, loose clothing that feels less restrictive."),
    relaxCase(86, "完成一次温和面部护理", "Do a gentle skincare routine", "用熟悉且适合自己的产品，缓慢完成清洁和保湿。", "Use familiar suitable products and slowly cleanse and moisturize."),
    relaxCase(87, "安静拼十分钟拼图", "Work on a puzzle for ten minutes", "选择简单区域，不追求一次完成整幅拼图。", "Choose an easy section without trying to finish the whole puzzle."),
    relaxCase(88, "给植物擦一次叶片", "Wipe a plant's leaves", "用柔软湿布轻轻清理叶面灰尘。", "Use a soft damp cloth to gently remove dust from the leaves."),
    relaxCase(89, "完成一次慢节奏早餐", "Have a slow breakfast", "预留足够时间坐下吃饭，不边走边吃。", "Leave enough time to sit and eat instead of eating on the move."),
    relaxCase(90, "给自己安排一小时空白时间", "Reserve one unscheduled hour", "不设置产出目标，只做真正想做的安静活动。", "Set no productivity goal and choose a genuinely restful activity."),
    relaxCase(91, "完成十五分钟正念练习", "Complete a fifteen-minute mindfulness practice", "选择引导音频或关注呼吸，走神时温和返回。", "Use guided audio or focus on breathing, returning gently when distracted."),
    relaxCase(92, "尝试渐进式肌肉放松", "Try progressive muscle relaxation", "从脚到脸依次绷紧再放松肌肉，避免用力过度。", "Tense and release muscles from feet to face without straining."),
    relaxCase(93, "安排一个无屏幕夜晚", "Plan a screen-free evening", "提前准备阅读、散步或手工活动，减少临时拿起手机。", "Prepare reading, walking, or crafts so you are less tempted to reach for a phone."),
    relaxCase(94, "完成一次半小时独处", "Spend thirty minutes alone", "选择安全安静的空间，暂时不回应非紧急消息。", "Choose a safe quiet space and pause nonurgent replies."),
    relaxCase(95, "制定一周放松清单", "Create a weekly relaxation list", "为每天安排一项十分钟以内的简单放松活动。", "Assign one simple activity under ten minutes to each day."),
    relaxCase(96, "进行一次一小时自然散步", "Take a one-hour nature walk", "选择安全路线，准备饮水并保持轻松节奏。", "Choose a safe route, carry water, and maintain an easy pace."),
    relaxCase(97, "完成一个周末低刺激计划", "Plan a low-stimulation weekend", "减少过密安排，为睡眠、散步和安静活动留出时间。", "Reduce packed scheduling and leave time for sleep, walking, and quiet activities."),
    relaxCase(98, "设计个人恢复清单", "Create a personal recovery list", "列出疲惫时真正有帮助的人、地点和活动。", "List the people, places, and activities that genuinely help when you are tired."),
    relaxCase(99, "完成一次全天数字休息", "Take a full-day digital break", "提前通知必要联系人，并准备离线活动和紧急联系方式。", "Notify essential contacts and prepare offline activities and emergency access."),
    relaxCase(100, "建立一个月放松习惯", "Build a one-month relaxation routine", "每天选择一个短活动，坚持记录时间和完成后的感受。", "Choose one short activity each day and track the time and how you feel afterward."),
)

private fun relaxCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-relax-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_relax,
    imageAsset = "relax",
)
