package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun socialRecommendationCases(): List<RecommendationCase> = listOf(
    socialCase(1, "给朋友发一句问候", "Send a greeting to a friend", "选一位朋友，简单问问对方今天过得怎么样。", "Choose a friend and simply ask how their day is going."),
    socialCase(2, "向家人说声早安", "Say good morning to family", "用一句自然的问候开始今天的家庭交流。", "Begin today's family interaction with a natural greeting."),
    socialCase(3, "对同事说一句谢谢", "Thank a colleague", "具体说出对方哪一件小事帮助了你。", "Mention one specific thing the colleague did that helped you."),
    socialCase(4, "回复一条搁置的消息", "Reply to a delayed message", "处理一条一直没有回复的私人消息，并说明迟复原因。", "Answer one personal message you postponed and briefly acknowledge the delay."),
    socialCase(5, "给朋友分享一张照片", "Share a photo with a friend", "发送一张今天拍的照片，并补充一句背景。", "Send a photo from today with one sentence of context."),
    socialCase(6, "向邻居打个招呼", "Greet a neighbor", "遇见邻居时自然问候，不必展开很长的交谈。", "Offer a natural greeting without needing a long conversation."),
    socialCase(7, "夸奖一个人的努力", "Compliment someone's effort", "关注对方付出的过程，而不只评价最终结果。", "Recognize the effort someone made, not only the final result."),
    socialCase(8, "问候一位老朋友", "Check in with an old friend", "给一位许久没联系的人发一条不带压力的消息。", "Send a low-pressure message to someone you have not contacted recently."),
    socialCase(9, "给家人倒一杯水", "Bring a family member some water", "用一个简单行动表达你对家人的关心。", "Show care for a family member through one simple action."),
    socialCase(10, "记住一个人的名字", "Remember someone's name", "遇到新认识的人时，认真听清并在交流中使用一次名字。", "Listen carefully to a new person's name and use it once in conversation."),
    socialCase(11, "认真听朋友说五分钟", "Listen to a friend for five minutes", "先不急着给建议，让对方完整说完正在经历的事情。", "Avoid rushing into advice and let your friend finish what they are sharing."),
    socialCase(12, "问一个开放式问题", "Ask an open-ended question", "使用不能只回答是或否的问题，让交流更自然地展开。", "Ask something that cannot be answered only with yes or no."),
    socialCase(13, "聊天时暂时放下手机", "Put your phone away during a conversation", "把注意力放在眼前的人和正在进行的对话上。", "Give your attention to the person and conversation in front of you."),
    socialCase(14, "复述一次对方的意思", "Reflect back what someone said", "用自己的话确认理解，避免误会对方的重点。", "Restate the main point in your own words to avoid misunderstanding."),
    socialCase(15, "询问朋友最近的变化", "Ask about a friend's recent changes", "从工作、学习或生活中选一个具体方向进行关心。", "Ask specifically about one area such as work, study, or daily life."),
    socialCase(16, "忍住一次打断", "Avoid interrupting once", "即使想到回应，也等对方说完当前这句话。", "Even when a response comes to mind, wait until the person finishes."),
    socialCase(17, "关注一次对方的情绪", "Notice someone's emotion", "留意语气和表情，再温和询问对方是否还好。", "Notice tone and expression, then gently ask whether they are okay."),
    socialCase(18, "请对方多讲一点", "Invite someone to say more", "对感兴趣的内容表达好奇，让对方继续分享。", "Show curiosity about an interesting point and invite more detail."),
    socialCase(19, "聊天后记住一个细节", "Remember one conversation detail", "记下一项对方在意的事情，方便以后继续关心。", "Remember one thing that matters to the person for a future follow-up."),
    socialCase(20, "用一句话确认感受", "Acknowledge someone's feelings", "不急着判断对错，先表达你理解对方的感受。", "Before judging the situation, show that you understand how they feel."),
    socialCase(21, "给帮助过你的人道谢", "Thank someone who helped you", "说明这份帮助具体为你解决了什么问题。", "Explain what problem their help solved for you."),
    socialCase(22, "写一条感谢消息", "Write a thank-you message", "用两三句话表达感谢，并避免只写一句客套话。", "Use two or three sincere sentences instead of a generic phrase."),
    socialCase(23, "感谢一位服务人员", "Thank a service worker", "在接受服务后清楚表达感谢并保持礼貌。", "Clearly express thanks and remain courteous after receiving service."),
    socialCase(24, "赞美朋友的一项优点", "Praise a friend's quality", "选择一个真实具体的优点，告诉对方你为何欣赏。", "Choose a genuine quality and explain why you appreciate it."),
    socialCase(25, "认可同事的一次进步", "Recognize a colleague's improvement", "指出你观察到的具体变化和积极影响。", "Point out the specific improvement and its positive effect."),
    socialCase(26, "感谢家人的日常付出", "Thank family for everyday effort", "选择一件容易被忽略的家务或照顾表达感谢。", "Acknowledge one often-overlooked household or caring effort."),
    socialCase(27, "给朋友写一张小卡片", "Write a small card for a friend", "写下一句感谢或祝福，亲手交给对方。", "Write a brief thanks or good wish and give it to them personally."),
    socialCase(28, "向老师表达一次感谢", "Thank a teacher", "说明哪次教导或建议对你产生了帮助。", "Mention which lesson or piece of advice helped you."),
    socialCase(29, "公开肯定团队伙伴", "Recognize a teammate publicly", "在合适场合具体肯定对方的贡献，不夸大事实。", "Acknowledge a teammate's contribution specifically and accurately."),
    socialCase(30, "记录今天收到的善意", "Record kindness you received today", "写下一个别人对你友好的瞬间，以及你的感受。", "Write down one kind moment from someone else and how it felt."),
    socialCase(31, "和父母聊十分钟", "Talk with your parents for ten minutes", "询问他们今天做了什么，并分享一点自己的近况。", "Ask about their day and share a little about your own."),
    socialCase(32, "给远方亲人打电话", "Call a relative who lives far away", "安排一段不匆忙的时间，了解对方最近的生活。", "Set aside unrushed time to hear how they have been."),
    socialCase(33, "和家人一起吃顿饭", "Have a meal with family", "尽量同时坐下来吃饭，并聊聊当天发生的小事。", "Sit down together when possible and talk about small events from the day."),
    socialCase(34, "问家人一个童年故事", "Ask for a family childhood story", "请一位家人讲一件小时候印象深刻的事情。", "Ask a family member to share a memorable childhood event."),
    socialCase(35, "帮家人完成一件小事", "Help a family member with one task", "主动处理一件对方正准备做的简单事情。", "Take care of one simple task they were about to do."),
    socialCase(36, "和家人看一集节目", "Watch one program with family", "共同选择内容，并在结束后交流一两句感受。", "Choose something together and exchange a few thoughts afterward."),
    socialCase(37, "给长辈分享一张近照", "Share a recent photo with an elder", "发送一张清晰照片，并告诉对方照片中的故事。", "Send a clear photo and explain the story behind it."),
    socialCase(38, "记住一个家庭纪念日", "Remember a family anniversary", "把重要日期记入日历，并提前设置提醒。", "Add an important date to your calendar and set an early reminder."),
    socialCase(39, "整理一张家庭合影", "Organize one family photo", "为照片补充时间、地点和人物信息。", "Add the date, place, and names of the people in the photo."),
    socialCase(40, "和家人商量周末安排", "Discuss weekend plans with family", "听取每个人的想法，再确定一个大家都能接受的安排。", "Hear everyone's ideas before choosing a plan that works for all."),
    socialCase(41, "邀请朋友一起散步", "Invite a friend for a walk", "提出一个明确时间和地点，让邀请容易回应。", "Suggest a clear time and place so the invitation is easy to answer."),
    socialCase(42, "约朋友喝一杯饮品", "Invite a friend for a drink", "选择双方方便的地点，安排一次轻松见面。", "Choose a convenient place for a relaxed meetup."),
    socialCase(43, "给朋友推荐一首歌", "Recommend a song to a friend", "说明你为什么想到把这首歌分享给对方。", "Explain why this song made you think of them."),
    socialCase(44, "给朋友推荐一本书", "Recommend a book to a friend", "根据对方兴趣推荐，并简单介绍值得读的地方。", "Match the recommendation to their interests and explain its appeal."),
    socialCase(45, "和朋友交换近况", "Exchange life updates with a friend", "双方各分享一件最近开心和一件困扰的事情。", "Each share one recent joy and one current difficulty."),
    socialCase(46, "陪朋友完成一件小事", "Accompany a friend on a small task", "在对方需要时陪同办事、购物或等待。", "Join them for an errand, shopping trip, or period of waiting."),
    socialCase(47, "和朋友吃一顿午饭", "Have lunch with a friend", "提前约好时间，吃饭时尽量不处理工作消息。", "Arrange the time in advance and avoid work messages during the meal."),
    socialCase(48, "分享一个实用链接", "Share a useful link", "确认内容可靠且适合对方，再补充一句推荐理由。", "Check that it is reliable and relevant, then add why you recommend it."),
    socialCase(49, "问朋友是否需要帮助", "Ask whether a friend needs help", "针对具体事情询问，避免只说一句宽泛的客套话。", "Ask about a specific situation rather than making a vague offer."),
    socialCase(50, "兑现一次朋友间的约定", "Keep a promise to a friend", "按约定完成答应的事情，若有变化及时说明。", "Do what you promised and communicate early if anything changes."),
    socialCase(51, "和同事进行一次午间交流", "Have a lunchtime chat with a colleague", "聊聊工作之外的轻松话题，增进彼此了解。", "Talk about something light beyond work and get to know each other."),
    socialCase(52, "向同事请教一个问题", "Ask a colleague for advice", "先说明自己尝试过什么，再提出清晰问题。", "Explain what you have tried, then ask a clear question."),
    socialCase(53, "帮助同事处理一个小问题", "Help a colleague with a small problem", "在能力范围内提供具体帮助，不替对方完全接管。", "Offer practical help within your ability without taking over entirely."),
    socialCase(54, "邀请新同事一起吃饭", "Invite a new colleague to lunch", "用轻松方式发出邀请，让对方可以自由选择。", "Invite them casually and make it easy to decline."),
    socialCase(55, "分享一条工作经验", "Share one work tip", "选择一个真正实用的小技巧，并说明适用场景。", "Share a genuinely useful tip and explain when it applies."),
    socialCase(56, "询问同事的意见", "Ask for a colleague's opinion", "在做决定前听取一个不同视角。", "Seek another perspective before making a decision."),
    socialCase(57, "向团队同步一次好消息", "Share good news with the team", "清楚说明成果，并感谢参与者的贡献。", "Explain the result clearly and acknowledge those who contributed."),
    socialCase(58, "为同事庆祝一个小成果", "Celebrate a colleague's small win", "用一句祝贺或一个简单行动认可对方。", "Recognize their achievement with a congratulation or small gesture."),
    socialCase(59, "主动介绍两位合适的人认识", "Introduce two people who should meet", "说明双方可能的共同话题，并征得彼此同意。", "Explain their common interest and get consent before connecting them."),
    socialCase(60, "结束一次带有误会的对话", "Resolve a misunderstood conversation", "平静确认事实和意思，让双方回到共同目标。", "Clarify facts and intent calmly so both sides return to a shared goal."),
    socialCase(61, "参加一次社区活动", "Join a community activity", "选择感兴趣的小型活动，至少与一位参与者交流。", "Choose a small event you like and speak with at least one participant."),
    socialCase(62, "去一次兴趣小组", "Attend an interest group", "参加与阅读、运动或手工相关的线下或线上活动。", "Join an online or in-person group for reading, sport, crafts, or another interest."),
    socialCase(63, "和陌生人进行一次礼貌交流", "Have one polite exchange with a stranger", "在自然场景中进行简短、安全且有边界的交流。", "Have a brief, safe, and respectful exchange in a natural setting."),
    socialCase(64, "向活动组织者表示感谢", "Thank an event organizer", "活动结束后说明你最喜欢的一个环节。", "After the event, mention the part you enjoyed most."),
    socialCase(65, "参与一次志愿服务", "Join a volunteer activity", "选择正规项目，按要求完成一段力所能及的服务。", "Choose a legitimate program and complete a manageable period of service."),
    socialCase(66, "在群聊中回答一个问题", "Answer one group-chat question", "只在确定信息准确时回复，并保持内容简洁。", "Reply only when confident the information is accurate and keep it concise."),
    socialCase(67, "分享一条本地信息", "Share one local update", "核实时间和地点后，把有用信息发给可能需要的人。", "Verify the time and place before sharing useful local information."),
    socialCase(68, "认识一位兴趣相近的人", "Meet someone with a shared interest", "从共同爱好开始交流，不急于询问私人信息。", "Begin with the shared interest and avoid rushing into personal questions."),
    socialCase(69, "参加一次公开讲座", "Attend a public talk", "听完后和身边的人交换一个观点或问题。", "Afterward, exchange one thought or question with someone nearby."),
    socialCase(70, "为社区提出一个小建议", "Offer one small community suggestion", "说明具体问题和可行改进方式，保持表达友善。", "Describe the issue and a practical improvement in a respectful way."),
    socialCase(71, "主动为一次疏忽道歉", "Apologize for one oversight", "直接承认影响，不用借口淡化问题。", "Acknowledge the impact directly without minimizing it with excuses."),
    socialCase(72, "接受一次真诚道歉", "Accept a sincere apology", "在愿意的情况下明确回应，并说明后续需要什么。", "When ready, respond clearly and explain what is needed next."),
    socialCase(73, "澄清一个小误会", "Clarify a small misunderstanding", "用事实和自己的感受说明情况，避免猜测动机。", "Use facts and your feelings without guessing the other person's motives."),
    socialCase(74, "表达一次不同意见", "Express a disagreement respectfully", "先确认共同点，再清楚说明自己的理由。", "Acknowledge common ground before explaining your reasoning."),
    socialCase(75, "拒绝一次不方便的邀请", "Decline an inconvenient invitation", "简洁表达无法参加，不编造复杂理由。", "Say clearly that you cannot attend without inventing an elaborate excuse."),
    socialCase(76, "提出一个具体边界", "State one clear boundary", "说明自己能接受和不能接受的行为或时间安排。", "Explain which behavior or schedule you can and cannot accept."),
    socialCase(77, "停止一次无效争论", "Pause an unproductive argument", "在情绪升高时暂停，并约定更合适的沟通时间。", "Pause when emotions rise and agree on a better time to talk."),
    socialCase(78, "请求对方给你一点时间", "Ask for time to respond", "需要思考时明确说明，而不是勉强立即答应。", "When you need to think, say so instead of agreeing immediately."),
    socialCase(79, "修复一次失约", "Repair a missed commitment", "承认失约并提出一个具体可执行的补救办法。", "Acknowledge the missed commitment and offer a concrete repair."),
    socialCase(80, "和解后确认下一步", "Agree on the next step after resolving conflict", "把双方同意的行动和时间说清楚。", "Clarify the action and timing both people have agreed to."),
    socialCase(81, "组织一次三人聚餐", "Organize a meal for three", "确认时间、地点和饮食偏好，再完成预约。", "Confirm the time, place, and food preferences before booking."),
    socialCase(82, "举办一次家庭游戏夜", "Host a family game night", "选择规则简单的游戏，并让每个人都有参与机会。", "Choose an easy game and make sure everyone can participate."),
    socialCase(83, "安排一次朋友散步局", "Plan a group walk with friends", "选择安全路线、集合点和大致结束时间。", "Choose a safe route, meeting point, and approximate finish time."),
    socialCase(84, "组织一次线上聊天", "Host an online catch-up", "提前确定时间和时长，让远方朋友也能参加。", "Set the time and duration so distant friends can join."),
    socialCase(85, "为朋友准备一个小惊喜", "Prepare a small surprise for a friend", "根据对方喜好准备简单心意，不增加对方负担。", "Choose a thoughtful gesture that matches their taste without creating pressure."),
    socialCase(86, "举办一次交换书活动", "Host a book exchange", "邀请几位朋友各带一本书，并简单介绍推荐理由。", "Ask friends to bring one book and briefly explain why they recommend it."),
    socialCase(87, "组织一次共同做饭", "Organize a group cooking session", "提前分配采购、准备和清理任务。", "Assign shopping, preparation, and cleanup tasks in advance."),
    socialCase(88, "安排一次老友见面", "Arrange an old-friends reunion", "收集可行时间，选择多数人方便的日期。", "Gather available times and choose a date that works for most people."),
    socialCase(89, "策划一次生日聚会", "Plan a birthday gathering", "考虑主角偏好、人数、预算和时间，避免过度复杂。", "Consider preferences, group size, budget, and timing without overcomplicating it."),
    socialCase(90, "组织一次小型户外活动", "Organize a small outdoor activity", "确认天气、路线和安全事项，并准备备用方案。", "Check weather, route, and safety details and prepare a backup plan."),
    socialCase(91, "连续七天问候不同的人", "Greet a different person for seven days", "每天主动联系一位不同的人，并保持问候自然简短。", "Contact a different person each day with a brief, natural greeting."),
    socialCase(92, "整理一份重要联系人清单", "Organize an important contacts list", "补充关系、电话和必要备注，并妥善保护信息。", "Add relationships, phone numbers, and useful notes while protecting privacy."),
    socialCase(93, "完成一次关系近况复盘", "Review your important relationships", "想想最近联系较少的人，并选择一位重新建立联系。", "Notice someone you have contacted less and choose one person to reconnect with."),
    socialCase(94, "建立一个每月家庭通话安排", "Create a monthly family call routine", "和远方家人约定容易坚持的固定时间。", "Agree on a regular time that distant family members can maintain."),
    socialCase(95, "为朋友提供一次实际支持", "Offer practical support to a friend", "先确认对方真正需要什么，再提供力所能及的帮助。", "Ask what is actually needed before offering manageable help."),
    socialCase(96, "策划一次无手机聚会", "Plan a phone-free gathering", "提前征得大家同意，留出专心聊天和互动的时间。", "Get everyone's agreement and reserve time for focused conversation."),
    socialCase(97, "完成一次多人活动协调", "Coordinate a group activity", "统一时间、地点、分工和变更通知方式。", "Align the time, place, roles, and method for communicating changes."),
    socialCase(98, "建立一个共同兴趣小组", "Start a shared-interest group", "确定主题、人数和简单规则，安排第一次活动。", "Choose a theme, group size, simple rules, and the first activity."),
    socialCase(99, "组织一次公益筹备活动", "Organize a small charitable effort", "选择可信项目，明确目标、分工和公开记录方式。", "Choose a trusted cause and define the goal, roles, and transparent tracking."),
    socialCase(100, "完成一个月主动联系计划", "Complete a one-month connection plan", "每周联系几位重要的人，并记录交流后的感受和后续。", "Contact several important people each week and note feelings and follow-ups."),
)

private fun socialCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-social-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_social,
    imageAsset = "social",
)
