package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun sportRecommendationCases(): List<RecommendationCase> = listOf(
    sportCase(1, "散步十分钟", "Take a ten-minute walk", "选择安全平坦的路线，用轻松速度走十分钟。", "Choose a safe, level route and walk at an easy pace for ten minutes."),
    sportCase(2, "饭后散步二十分钟", "Walk for twenty minutes after dinner", "饭后稍作休息，再用舒适速度完成一次散步。", "Rest briefly after dinner, then take a comfortable twenty-minute walk."),
    sportCase(3, "做十次深蹲", "Do ten squats", "双脚站稳并保持背部自然，缓慢完成十次深蹲。", "Stand firmly, keep a natural back position, and complete ten slow squats."),
    sportCase(4, "做十次靠墙俯卧撑", "Do ten wall push-ups", "面对墙壁保持身体稳定，完成十次轻量推撑。", "Face a wall, keep your body stable, and complete ten gentle push-ups."),
    sportCase(5, "原地踏步五分钟", "March in place for five minutes", "抬起双脚并自然摆臂，让身体逐渐热起来。", "Lift your feet and swing your arms naturally to warm up."),
    sportCase(6, "拉伸肩颈五分钟", "Stretch your neck and shoulders", "动作保持缓慢，不要强拉疼痛或僵硬的位置。", "Move slowly and avoid forcing any painful or stiff area."),
    sportCase(7, "活动手腕一分钟", "Mobilize your wrists for one minute", "轻轻转动手腕，再分别拉伸手掌和手指。", "Gently rotate your wrists, then stretch your palms and fingers."),
    sportCase(8, "活动脚踝一分钟", "Mobilize your ankles for one minute", "扶稳身体，分别缓慢转动左右脚踝。", "Hold onto support and slowly rotate each ankle."),
    sportCase(9, "做十次提踵", "Do ten calf raises", "扶住稳定物体，缓慢抬起脚跟再轻轻落下。", "Hold a stable surface, raise your heels slowly, then lower them gently."),
    sportCase(10, "做五次坐站练习", "Do five sit-to-stands", "从稳固椅子上起身再坐下，保持动作受控。", "Stand from a stable chair and sit again with controlled movement."),
    sportCase(11, "跟练三分钟热身操", "Follow a three-minute warm-up", "选择简单动作，让肩、髋、膝和脚踝逐渐进入状态。", "Use simple movements to prepare your shoulders, hips, knees, and ankles."),
    sportCase(12, "伸展背部两分钟", "Stretch your back for two minutes", "通过猫牛式或站立伸展，温和活动背部。", "Use cat-cow or standing stretches to move your back gently."),
    sportCase(13, "做十次侧抬腿", "Do ten side leg raises", "扶稳身体，左右腿各完成五次侧向抬起。", "Hold support and raise each leg to the side five times."),
    sportCase(14, "练习单脚站立", "Practice standing on one leg", "靠近墙面，左右脚各尝试保持十秒。", "Stand near a wall and balance for ten seconds on each foot."),
    sportCase(15, "完成一次全身伸展", "Complete a full-body stretch", "从颈部到小腿依次伸展，每个动作保持舒适。", "Stretch from your neck to your calves, keeping every position comfortable."),
    sportCase(16, "走完一千步", "Walk one thousand steps", "分一次或多次完成今天的一千步轻量活动。", "Complete one thousand easy steps in one or several sessions."),
    sportCase(17, "做十次手臂绕环", "Do ten arm circles", "保持肩膀放松，向前和向后各绕环五次。", "Relax your shoulders and circle forward and backward five times each."),
    sportCase(18, "做一分钟扩胸运动", "Do one minute of chest-opening movements", "配合呼吸打开胸肩，避免快速甩动手臂。", "Open your chest and shoulders with your breath without swinging quickly."),
    sportCase(19, "踮脚走二十步", "Walk twenty steps on your toes", "在平坦地面缓慢前进，必要时扶墙保持平衡。", "Move slowly on a flat surface and use a wall for balance if needed."),
    sportCase(20, "脚跟走二十步", "Walk twenty steps on your heels", "抬起前脚掌缓慢行走，保持上身稳定。", "Lift the front of your feet, walk slowly, and keep your upper body steady."),
    sportCase(21, "快走十五分钟", "Take a fifteen-minute brisk walk", "用比散步稍快的速度行走，同时保持能够正常说话。", "Walk faster than a stroll while remaining able to speak comfortably."),
    sportCase(22, "慢跑五分钟", "Jog for five minutes", "先充分热身，再用轻松速度完成短时间慢跑。", "Warm up first, then jog at an easy pace for five minutes."),
    sportCase(23, "慢跑一公里", "Jog one kilometer", "控制呼吸和速度，不追求用时，顺利完成即可。", "Control your breathing and pace without chasing a fast time."),
    sportCase(24, "跳绳五十下", "Do fifty jump-rope skips", "选择平整场地，可分组完成并注意落地缓冲。", "Use a level surface, split the skips into sets, and land softly."),
    sportCase(25, "做十五次深蹲", "Do fifteen squats", "让膝盖朝向脚尖方向，保持动作稳定流畅。", "Keep your knees aligned with your toes and move steadily."),
    sportCase(26, "做十次跪姿俯卧撑", "Do ten kneeling push-ups", "收紧躯干并控制下降幅度，按能力完成。", "Brace your torso and control the lowering range according to your ability."),
    sportCase(27, "完成二十秒平板支撑", "Hold a plank for twenty seconds", "保持头、背和髋部大致成一条直线。", "Keep your head, back, and hips roughly aligned."),
    sportCase(28, "做十次臀桥", "Do ten glute bridges", "仰卧屈膝，缓慢抬起髋部并控制落下。", "Lie with bent knees, lift your hips slowly, and lower with control."),
    sportCase(29, "做十次弓步练习", "Do ten lunges", "左右交替完成，步幅以膝盖舒适为准。", "Alternate legs and choose a stride that feels comfortable for your knees."),
    sportCase(30, "爬五层楼梯", "Climb five flights of stairs", "根据体力调整速度，扶好扶手并留意脚下。", "Adjust your pace, use the handrail, and watch your footing."),
    sportCase(31, "完成十分钟健身操", "Complete a ten-minute cardio routine", "选择低冲击动作，保持身体微微发热即可。", "Choose low-impact moves and aim for a gentle rise in body temperature."),
    sportCase(32, "做二十次开合步", "Do twenty step jacks", "用左右迈步代替跳跃，配合手臂完成动作。", "Step side to side instead of jumping and coordinate your arms."),
    sportCase(33, "做二十次登山步", "Do twenty mountain climbers", "双手支撑稳定，左右腿交替向前移动。", "Keep your hands stable and alternate bringing each leg forward."),
    sportCase(34, "侧向行走二十步", "Take twenty lateral steps", "微屈膝盖，向左右各移动十步。", "Bend your knees slightly and take ten steps in each direction."),
    sportCase(35, "练习高抬腿三十秒", "Do thirty seconds of high knees", "根据能力抬腿，可用快走形式降低冲击。", "Lift your knees to a comfortable height or march to reduce impact."),
    sportCase(36, "完成一次八分钟间歇走", "Complete an eight-minute interval walk", "快走一分钟、慢走一分钟，交替完成四组。", "Alternate one minute fast and one minute easy for four rounds."),
    sportCase(37, "绕小区走两圈", "Walk two laps around the neighborhood", "选择熟悉安全的路线，保持均匀速度完成。", "Use a familiar safe route and maintain a steady pace."),
    sportCase(38, "骑车二十分钟", "Cycle for twenty minutes", "检查刹车和轮胎，在安全路段轻松骑行。", "Check the brakes and tires, then ride easily on a safe route."),
    sportCase(39, "跳一支简单舞蹈", "Dance to one simple routine", "跟随喜欢的音乐活动全身，不要求动作标准。", "Move your whole body to music without worrying about perfect technique."),
    sportCase(40, "打一场轻松羽毛球", "Play a casual badminton game", "和伙伴进行轻松对打，以连续回合和活动身体为主。", "Play relaxed rallies with a partner and focus on keeping moving."),
    sportCase(41, "练习五分钟瑜伽呼吸", "Practice five minutes of yoga breathing", "保持舒适坐姿，让呼吸缓慢而均匀。", "Sit comfortably and let your breathing become slow and even."),
    sportCase(42, "完成一组猫牛式", "Complete a set of cat-cow stretches", "配合呼吸缓慢活动脊柱，共完成十次。", "Move your spine slowly with your breath for ten repetitions."),
    sportCase(43, "练习下犬式三次", "Practice downward dog three times", "每次短暂保持，膝盖可以微屈以保护腿后侧。", "Hold briefly each time and bend your knees if your hamstrings feel tight."),
    sportCase(44, "练习婴儿式两分钟", "Rest in child's pose for two minutes", "让背部和肩膀放松，保持自然呼吸。", "Relax your back and shoulders while breathing naturally."),
    sportCase(45, "做五分钟髋部拉伸", "Stretch your hips for five minutes", "选择弓步或坐姿动作，左右两侧均匀完成。", "Use lunging or seated stretches and work both sides evenly."),
    sportCase(46, "做五分钟腿后侧拉伸", "Stretch your hamstrings for five minutes", "保持背部自然，只拉到轻微紧张的位置。", "Keep your back neutral and stop at a mild stretching sensation."),
    sportCase(47, "放松小腿三分钟", "Relax your calves for three minutes", "靠墙拉伸左右小腿，每侧保持舒适时间。", "Use a wall stretch on each calf and hold comfortably."),
    sportCase(48, "做一次睡前舒缓拉伸", "Do a gentle bedtime stretch", "选择缓慢动作，避免让心率明显升高。", "Choose slow movements that do not raise your heart rate much."),
    sportCase(49, "用泡沫轴放松大腿", "Foam-roll your thighs", "缓慢滚动大腿肌肉，避开关节和明显疼痛点。", "Roll the thigh muscles slowly and avoid joints or sharp pain."),
    sportCase(50, "练习十分钟基础瑜伽", "Practice ten minutes of basic yoga", "组合呼吸、站立和地面动作，保持过程舒适。", "Combine breathing, standing, and floor poses while staying comfortable."),
    sportCase(51, "做两组十次深蹲", "Do two sets of ten squats", "两组之间休息一分钟，保持每次动作质量。", "Rest for one minute between sets and maintain good form."),
    sportCase(52, "做两组八次俯卧撑", "Do two sets of eight push-ups", "可选择墙面、跪姿或标准姿势完成。", "Use wall, kneeling, or standard push-ups according to your level."),
    sportCase(53, "做三组十次臀桥", "Do three sets of ten glute bridges", "每组之间短暂休息，感受臀部主动发力。", "Rest briefly between sets and focus on using your glutes."),
    sportCase(54, "完成三十秒平板支撑", "Hold a plank for thirty seconds", "保持核心收紧，腰部不明显下沉或抬高。", "Brace your core without letting your lower back sag or lift."),
    sportCase(55, "做两组十次反向弓步", "Do two sets of reverse lunges", "向后迈步并保持前脚稳定，左右交替完成。", "Step backward, stabilize the front foot, and alternate sides."),
    sportCase(56, "做十五次鸟狗式", "Do fifteen bird-dogs", "从四足姿势交替伸展对侧手脚，保持躯干稳定。", "From all fours, extend opposite limbs while keeping your torso steady."),
    sportCase(57, "做十五次死虫式", "Do fifteen dead bugs", "腰背贴稳地面，缓慢交替伸展手脚。", "Keep your lower back supported and alternate limbs slowly."),
    sportCase(58, "完成十分钟核心训练", "Complete a ten-minute core workout", "组合平板、鸟狗和臀桥，并在动作间短暂休息。", "Combine planks, bird-dogs, and bridges with short rests."),
    sportCase(59, "做两组十二次提踵", "Do two sets of twelve calf raises", "在动作顶端短暂停留，再缓慢落下脚跟。", "Pause briefly at the top before lowering your heels slowly."),
    sportCase(60, "完成十五分钟自重训练", "Complete a fifteen-minute bodyweight workout", "组合深蹲、推撑和核心动作，按能力调整次数。", "Combine squats, pushing, and core work, adjusting repetitions as needed."),
    sportCase(61, "连续快走三十分钟", "Walk briskly for thirty minutes", "保持稳定节奏，结束前用几分钟逐渐放慢。", "Maintain a steady pace and slow down gradually near the end."),
    sportCase(62, "轻松慢跑十五分钟", "Jog easily for fifteen minutes", "用能维持对话的速度慢跑，不追求距离。", "Jog at a conversational pace without focusing on distance."),
    sportCase(63, "完成两公里步行", "Complete a two-kilometer walk", "记录大致用时和身体感受，途中可以短暂休息。", "Note your approximate time and how you feel, resting briefly if needed."),
    sportCase(64, "完成三公里骑行", "Complete a three-kilometer ride", "选择车流较少的路线，遵守交通规则完成骑行。", "Choose a low-traffic route and follow traffic rules throughout."),
    sportCase(65, "游泳二十分钟", "Swim for twenty minutes", "在有安全保障的泳池内，按自己的节奏游泳。", "Swim at your own pace in a properly supervised pool."),
    sportCase(66, "打三十分钟乒乓球", "Play table tennis for thirty minutes", "和伙伴轻松对打，注意热身手腕和肩部。", "Play casual rallies and warm up your wrists and shoulders first."),
    sportCase(67, "踢二十分钟足球", "Play football for twenty minutes", "以传球和轻量跑动为主，避免突然过度冲刺。", "Focus on passing and light movement rather than sudden hard sprints."),
    sportCase(68, "投篮五十次", "Take fifty basketball shots", "分组完成投篮，记录命中次数和最舒服的位置。", "Split the shots into sets and note makes and your most comfortable spot."),
    sportCase(69, "完成二十分钟爬坡走", "Walk uphill for twenty minutes", "选择坡度适中的路线，上坡放慢并注意呼吸。", "Choose a moderate incline, slow down uphill, and watch your breathing."),
    sportCase(70, "完成三十分钟有氧运动", "Complete thirty minutes of cardio", "选择快走、骑车或健身操，中途按需要补水。", "Choose brisk walking, cycling, or aerobics and hydrate as needed."),
    sportCase(71, "进行一次五分钟热身", "Complete a five-minute warm-up", "正式运动前活动主要关节，并逐渐提高动作幅度。", "Move your major joints and gradually increase range before exercise."),
    sportCase(72, "运动后慢走五分钟", "Cool down with a five-minute walk", "训练结束后不要立刻停下，用慢走逐渐降低心率。", "Do not stop abruptly after training; walk slowly to lower your heart rate."),
    sportCase(73, "记录一次运动心情", "Record your post-workout mood", "写下运动前后精神和情绪的变化。", "Write down how your energy and mood changed after exercise."),
    sportCase(74, "记录一次运动时长", "Record one workout duration", "从热身到放松记录完整用时，了解实际活动量。", "Track the full time from warm-up through cool-down."),
    sportCase(75, "运动后补充一杯水", "Drink water after exercise", "训练结束后小口补水，不要一次喝得过快。", "Sip water after training instead of drinking too quickly."),
    sportCase(76, "清洗一次运动水杯", "Clean your sports bottle", "彻底清洗瓶盖和杯体，并晾干后再收好。", "Wash the bottle and lid thoroughly and let them dry."),
    sportCase(77, "整理一套运动装备", "Prepare a workout outfit", "把衣服、鞋袜和毛巾放在一起，方便下次使用。", "Place clothing, shoes, socks, and a towel together for next time."),
    sportCase(78, "检查一次运动鞋底", "Check your shoe soles", "查看磨损和异物，确认鞋底仍适合安全运动。", "Check wear and debris to ensure the soles remain safe for exercise."),
    sportCase(79, "学习一个正确动作", "Learn one exercise technique", "通过可靠教学了解动作要点，再用轻量方式练习。", "Use reliable instruction to learn the form, then practice lightly."),
    sportCase(80, "安排一个休息日", "Schedule a rest day", "在连续运动后留出恢复时间，进行轻量散步或伸展。", "Allow recovery after repeated workouts with only light walking or stretching."),
    sportCase(81, "完成三组力量循环", "Complete three strength circuits", "每组包含深蹲、推撑和臀桥，组间充分休息。", "Include squats, pushes, and bridges in each circuit with adequate rest."),
    sportCase(82, "完成二十分钟间歇快走", "Complete twenty minutes of interval walking", "两分钟快走与两分钟慢走交替，共完成五轮。", "Alternate two minutes fast and two minutes easy for five rounds."),
    sportCase(83, "尝试跑走交替训练", "Try a walk-run workout", "慢跑一分钟、步行两分钟，按体力完成五组。", "Jog for one minute and walk for two, completing up to five rounds."),
    sportCase(84, "完成一次五公里步行", "Complete a five-kilometer walk", "准备合适鞋袜和饮水，以舒适速度完成全程。", "Prepare suitable shoes and water, then walk at a comfortable pace."),
    sportCase(85, "完成一次五公里骑行", "Complete a five-kilometer ride", "提前规划安全路线，途中保持稳定速度。", "Plan a safe route in advance and maintain a steady speed."),
    sportCase(86, "连续练习瑜伽三十分钟", "Practice yoga for thirty minutes", "安排热身、主要体式和放松，动作难度循序渐进。", "Include warm-up, main poses, and relaxation with gradual difficulty."),
    sportCase(87, "完成一次全身力量训练", "Complete a full-body strength session", "覆盖腿部、推、拉和核心动作，并控制总量。", "Cover legs, pushing, pulling, and core work while controlling volume."),
    sportCase(88, "尝试一次节奏跑", "Try a tempo run", "充分热身后以略有挑战但可控制的速度短跑一段。", "After warming up, run briefly at a challenging but controlled pace."),
    sportCase(89, "完成一次球类综合练习", "Complete a mixed ball-sport practice", "练习传接、移动和简单对抗，并在结束后拉伸。", "Practice passing, movement, and light play, then stretch afterward."),
    sportCase(90, "挑战一天一万步", "Reach ten thousand steps in one day", "把步数分散到全天完成，不为数字勉强过度运动。", "Spread the steps across the day without forcing excessive activity."),
    sportCase(91, "制定一周散步计划", "Create a weekly walking plan", "安排每次时长、路线和休息日，让计划容易坚持。", "Set durations, routes, and rest days to make the plan sustainable."),
    sportCase(92, "制定一周基础力量计划", "Create a weekly strength plan", "选择三到五个动作，安排两到三次训练和恢复时间。", "Choose three to five movements and schedule two or three sessions with recovery."),
    sportCase(93, "连续七天完成晨间拉伸", "Complete seven days of morning stretching", "每天用五分钟活动身体，并记录最明显的变化。", "Stretch for five minutes each morning and note the clearest change."),
    sportCase(94, "连续四周记录步数", "Track steps for four weeks", "每周观察平均步数，只做小幅且可持续的调整。", "Review weekly averages and make only small sustainable changes."),
    sportCase(95, "设计一套二十分钟居家训练", "Design a twenty-minute home workout", "包含热身、力量、有氧和放松，并预留休息时间。", "Include warm-up, strength, cardio, cool-down, and rest periods."),
    sportCase(96, "为五公里活动做准备", "Prepare for a five-kilometer event", "用数周逐步增加步行或跑步距离，避免突然加量。", "Increase walking or running distance gradually over several weeks."),
    sportCase(97, "完成一次运动能力复盘", "Review your current fitness", "回顾耐力、力量、柔韧和平衡，选一个方向改进。", "Review endurance, strength, mobility, and balance, then choose one focus."),
    sportCase(98, "和朋友完成一次运动约定", "Complete a workout with a friend", "共同确定时间和项目，互相提醒并按计划完成。", "Agree on a time and activity, remind each other, and follow through."),
    sportCase(99, "参加一次入门运动课程", "Join a beginner exercise class", "选择适合新手的课程，提前告知教练自己的情况。", "Choose a beginner class and tell the instructor about relevant limitations."),
    sportCase(100, "制定一个月综合运动计划", "Create a one-month fitness plan", "合理组合有氧、力量、柔韧和休息，每周根据状态调整。", "Balance cardio, strength, mobility, and rest, adjusting each week as needed."),
)

private fun sportCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-sport-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_sport,
    imageAsset = "sport",
)
