package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun studyRecommendationCases(): List<RecommendationCase> = listOf(
    studyCase(1, "读一页书", "Read one page", "选择手边的一本书，专心读完一页内容。", "Choose a nearby book and read one page with full attention."),
    studyCase(2, "读一篇短文章", "Read a short article", "选一篇能在十分钟内读完的文章，并找出主要观点。", "Choose an article you can finish in ten minutes and identify its main point."),
    studyCase(3, "记住一个新单词", "Learn one new word", "记录读音、含义和一个简单例句。", "Record its pronunciation, meaning, and one simple example sentence."),
    studyCase(4, "复习一页旧笔记", "Review one page of notes", "重新阅读一页笔记，并标记仍然不清楚的地方。", "Reread one page of notes and mark anything still unclear."),
    studyCase(5, "做一道练习题", "Solve one practice problem", "独立完成一道题，再核对答案和步骤。", "Solve one problem independently, then check the answer and steps."),
    studyCase(6, "写下一个问题", "Write down one question", "记录今天真正想弄明白的一个问题。", "Write down one question you genuinely want to understand today."),
    studyCase(7, "朗读一段文字", "Read a passage aloud", "放慢速度，清楚读完一小段内容。", "Slow down and read a short passage clearly."),
    studyCase(8, "抄写一个公式", "Copy one formula", "写下公式，并标明每个符号代表什么。", "Write the formula and note what each symbol represents."),
    studyCase(9, "查清一个陌生术语", "Look up an unfamiliar term", "使用可靠来源确认定义，并用自己的话重述。", "Use a reliable source, then restate the definition in your own words."),
    studyCase(10, "整理学习桌面", "Tidy your study desk", "只保留本次学习需要的书、纸和文具。", "Keep only the books, paper, and stationery needed for this session."),
    studyCase(11, "连续阅读十分钟", "Read for ten minutes", "设置计时器，阅读期间不切换到其他内容。", "Set a timer and avoid switching to other content while reading."),
    studyCase(12, "标记三个关键词", "Mark three keywords", "从当前内容中选出三个最重要的词语。", "Choose the three most important terms from the current material."),
    studyCase(13, "总结一个自然段", "Summarize one paragraph", "用一句自己的话概括段落表达的核心意思。", "Use one sentence in your own words to capture the paragraph's main idea."),
    studyCase(14, "为文章写一个标题", "Write a title for an article", "读完内容后，用简短标题表达它的重点。", "After reading, create a short title that reflects the main point."),
    studyCase(15, "找出作者的结论", "Identify the author's conclusion", "区分事实、论据和最终主张。", "Distinguish the facts, supporting reasons, and final claim."),
    studyCase(16, "记录一个阅读疑问", "Record one reading question", "把读不懂或想继续追问的地方写下来。", "Write down one confusing point or question worth exploring."),
    studyCase(17, "比较文章的开头和结尾", "Compare an article's opening and ending", "观察作者如何提出问题以及如何收束内容。", "Notice how the author introduces the topic and brings it to a close."),
    studyCase(18, "读一篇不同观点的文章", "Read an article with a different viewpoint", "先理解对方的主要理由，再形成自己的看法。", "Understand the main reasoning before forming your own response."),
    studyCase(19, "为一篇文章做三条批注", "Add three annotations to an article", "分别记录重点、疑问和联想到的内容。", "Add one note each for a key point, a question, and a connection."),
    studyCase(20, "完成二十分钟深度阅读", "Complete twenty minutes of focused reading", "关闭通知，连续阅读并在结束后写一句总结。", "Turn off notifications, read continuously, and write one summary sentence."),
    studyCase(21, "制作一张知识卡片", "Create one flashcard", "正面写问题，背面写简洁准确的答案。", "Put a question on the front and a concise accurate answer on the back."),
    studyCase(22, "复习五张知识卡片", "Review five flashcards", "先主动回忆答案，再翻面检查。", "Recall each answer before turning the card over."),
    studyCase(23, "默写五个新单词", "Write five new words from memory", "不看资料写下单词，再检查拼写。", "Write the words without looking, then check their spelling."),
    studyCase(24, "回忆昨天学到的三点", "Recall three things from yesterday", "先不翻笔记，写出能记得的三个内容。", "Without checking notes, write three things you remember."),
    studyCase(25, "画一张记忆联想图", "Draw a memory association map", "把新知识和熟悉的人、地点或图像连接起来。", "Connect new information with familiar people, places, or images."),
    studyCase(26, "用口诀记一组内容", "Create a mnemonic", "把一组容易混淆的信息编成一句简短口诀。", "Turn a confusing set of facts into a short memorable phrase."),
    studyCase(27, "间隔复习一个旧知识点", "Review an older topic", "选择几天前学过的内容，测试自己还能记住多少。", "Choose something learned several days ago and test what remains."),
    studyCase(28, "闭书复述一个概念", "Explain a concept with the book closed", "不看资料讲出定义、用途和一个例子。", "Without notes, state the definition, use, and one example."),
    studyCase(29, "整理十张知识卡片", "Organize ten flashcards", "按掌握、模糊和不会分成三类。", "Sort them into known, uncertain, and unknown groups."),
    studyCase(30, "完成一次十五分钟记忆训练", "Complete fifteen minutes of memory practice", "组合主动回忆、核对和再次测试三个步骤。", "Combine active recall, checking, and retesting."),
    studyCase(31, "做三道基础题", "Solve three basic problems", "连续完成三道同类型题，确认基本步骤。", "Complete three problems of the same type to confirm the basic method."),
    studyCase(32, "改正一道错题", "Correct one wrong answer", "找到出错步骤，并写出正确做法。", "Locate the incorrect step and write the correct method."),
    studyCase(33, "为错题写原因", "Write why an answer was wrong", "区分概念不清、计算失误或审题错误。", "Identify whether the cause was concept, calculation, or reading."),
    studyCase(34, "重做一道旧题", "Redo an old problem", "不看原答案重新完成，再比较两次过程。", "Solve it again without the old answer, then compare both attempts."),
    studyCase(35, "给题目画示意图", "Draw a diagram for a problem", "把文字条件转换成简单图形或关系线。", "Turn the written conditions into a simple visual or relationship map."),
    studyCase(36, "检查一次计算单位", "Check calculation units", "确认所有数字的单位一致，结果单位合理。", "Ensure all inputs use compatible units and the result makes sense."),
    studyCase(37, "尝试第二种解法", "Try a second solution method", "完成常规方法后，再寻找另一条可行路径。", "After the usual method, look for another valid approach."),
    studyCase(38, "讲解一道题的步骤", "Explain a solution step by step", "假设正在教别人，清楚说明每一步为什么成立。", "Imagine teaching someone and explain why each step works."),
    studyCase(39, "完成一组限时练习", "Complete a timed practice set", "设定合理时间完成一小组题，并记录卡住的位置。", "Set a reasonable limit for a small set and note where you get stuck."),
    studyCase(40, "整理一页错题笔记", "Create one page of error notes", "记录题目类型、错误原因和下次提醒。", "Record the problem type, cause of error, and a reminder for next time."),
    studyCase(41, "写三条课堂笔记", "Write three class notes", "只记录关键概念、例子和老师强调的内容。", "Capture only key concepts, examples, and emphasized points."),
    studyCase(42, "整理一次笔记标题", "Improve your note headings", "为一页笔记增加清晰的主题和小标题。", "Add a clear topic and subheadings to one page of notes."),
    studyCase(43, "把长笔记缩成五行", "Reduce long notes to five lines", "保留核心内容，删除重复和次要信息。", "Keep the essentials and remove repeated or minor details."),
    studyCase(44, "给笔记增加一个例子", "Add an example to your notes", "用具体情境说明一个抽象概念。", "Use a concrete situation to explain an abstract idea."),
    studyCase(45, "画一张简单思维导图", "Draw a simple mind map", "从中心主题向外展开三到五个分支。", "Start with one central topic and add three to five branches."),
    studyCase(46, "用表格比较两个概念", "Compare two concepts in a table", "列出它们的定义、相同点和不同点。", "List their definitions, similarities, and differences."),
    studyCase(47, "给笔记标出重点层级", "Mark levels of importance in notes", "区分核心结论、支持信息和补充例子。", "Separate core conclusions, supporting details, and examples."),
    studyCase(48, "整理一次课堂录音要点", "Summarize a class recording", "只提取重要内容，不逐字抄写整段音频。", "Extract key ideas instead of transcribing every word."),
    studyCase(49, "把零散笔记合并成一页", "Merge scattered notes into one page", "去除重复内容，并按逻辑顺序重新排列。", "Remove duplication and arrange the material logically."),
    studyCase(50, "建立一个课程笔记目录", "Create a course note index", "列出主题、日期和对应文件或页码。", "List each topic, date, and matching file or page."),
    studyCase(51, "听十分钟知识播客", "Listen to ten minutes of an educational podcast", "选择一个明确主题，结束后记录一个观点。", "Choose a focused topic and record one idea afterward."),
    studyCase(52, "看一个短教学视频", "Watch a short tutorial", "观看十分钟以内的内容，并实际操作其中一步。", "Watch something under ten minutes and practice one demonstrated step."),
    studyCase(53, "暂停视频做一次预测", "Pause a lesson and predict the next step", "在答案出现前，先写下自己认为的结果。", "Before the answer appears, write what you think will happen."),
    studyCase(54, "调整一次课程播放速度", "Adjust lesson playback speed", "选择既能理解又不会拖慢注意力的速度。", "Choose a speed that remains understandable without losing attention."),
    studyCase(55, "给视频课程做三条笔记", "Take three notes from a video lesson", "记录核心概念、操作步骤和一个问题。", "Record a core concept, an action step, and one question."),
    studyCase(56, "跟做一次软件操作", "Follow one software demonstration", "暂停在每个关键步骤，自己完成后再继续。", "Pause at each important step and perform it before continuing."),
    studyCase(57, "比较两个教学来源", "Compare two learning sources", "查看它们对同一问题的解释是否一致。", "Check whether they explain the same topic consistently."),
    studyCase(58, "检查一个网络知识来源", "Evaluate an online source", "确认作者、日期、引用和发布机构是否可靠。", "Check the author, date, references, and publishing organization."),
    studyCase(59, "保存一个优质学习资源", "Save one quality learning resource", "放进明确分类，并写一句它适合解决什么问题。", "File it clearly and note what problem it helps solve."),
    studyCase(60, "完成一节线上课程", "Complete one online lesson", "看完内容、完成练习，并记录下一节要学什么。", "Finish the material and exercise, then note the next lesson."),
    studyCase(61, "学习五个英语单词", "Learn five English words", "记录发音、词义、词性和简单例句。", "Record pronunciation, meaning, word class, and a simple example."),
    studyCase(62, "朗读五句外语", "Read five foreign-language sentences aloud", "注意发音和停顿，并重复不流畅的句子。", "Focus on pronunciation and pauses, repeating any difficult sentence."),
    studyCase(63, "听一段一分钟外语音频", "Listen to one minute of foreign-language audio", "先听整体意思，再重听并捕捉关键词。", "Listen first for the general idea, then replay for keywords."),
    studyCase(64, "写五句外语日记", "Write five diary sentences in another language", "使用熟悉词汇描述今天发生的简单事情。", "Use familiar vocabulary to describe simple events from today."),
    studyCase(65, "模仿一段外语发音", "Shadow a short foreign-language clip", "逐句暂停并模仿语音、重音和节奏。", "Pause sentence by sentence and imitate sound, stress, and rhythm."),
    studyCase(66, "复习一个语法点", "Review one grammar point", "写下规则，并自己造两个不同例句。", "Write the rule and create two different example sentences."),
    studyCase(67, "完成一次单词听写", "Complete a vocabulary dictation", "播放或请人读出十个单词，再核对拼写。", "Hear ten words read aloud, write them, and check the spelling."),
    studyCase(68, "用外语介绍自己一分钟", "Introduce yourself for one minute", "准备姓名、兴趣和近况，并尝试流畅说完。", "Prepare your name, interests, and recent life, then speak continuously."),
    studyCase(69, "看一段带字幕的外语视频", "Watch a subtitled foreign-language clip", "先看目标语言字幕，必要时再查看翻译。", "Use target-language subtitles first and translation only if needed."),
    studyCase(70, "和语言伙伴交流十分钟", "Talk with a language partner for ten minutes", "提前准备两个简单话题，并记录不会表达的词。", "Prepare two simple topics and note words you could not express."),
    studyCase(71, "用自己的话解释一个概念", "Explain a concept in your own words", "避免照抄定义，使用简单语言和一个例子。", "Avoid copying the definition; use simple language and one example."),
    studyCase(72, "假装给新手讲课", "Teach the topic to a beginner", "从最基础的前提开始，逐步解释主要内容。", "Start from basic assumptions and explain the main ideas step by step."),
    studyCase(73, "回答一个为什么", "Answer one why question", "不仅写结论，还要补充原因和证据。", "Go beyond the conclusion by including reasons and evidence."),
    studyCase(74, "为知识点设计一道题", "Create a question about a topic", "写出题目、答案和判断答案正确的依据。", "Write the question, answer, and reason the answer is correct."),
    studyCase(75, "找出概念的反例", "Find a counterexample", "思考一个不符合常见结论的具体情况。", "Think of a specific case that challenges the usual conclusion."),
    studyCase(76, "用生活例子解释知识", "Explain knowledge with an everyday example", "把抽象内容连接到熟悉的生活场景。", "Connect an abstract idea to a familiar everyday situation."),
    studyCase(77, "录一段三分钟讲解", "Record a three-minute explanation", "不看稿讲清一个主题，再回听不顺畅之处。", "Explain a topic without a script, then replay areas that were unclear."),
    studyCase(78, "请别人向你提三个问题", "Ask someone to quiz you", "让对方围绕刚学内容提出三个不同问题。", "Have someone ask three different questions about what you learned."),
    studyCase(79, "写一份迷你教程", "Write a mini tutorial", "用五个步骤说明如何完成一项简单操作。", "Explain a simple process in five steps."),
    studyCase(80, "完成一次十分钟模拟教学", "Complete a ten-minute practice lesson", "安排开场、概念、例子、练习和总结。", "Include an opening, concept, example, exercise, and summary."),
    studyCase(81, "完成一次二十五分钟专注学习", "Complete a twenty-five-minute study session", "提前确定单一目标，结束后记录完成情况。", "Set one goal before starting and record the result afterward."),
    studyCase(82, "安排一个五分钟学习休息", "Take a five-minute study break", "离开座位活动身体，不用短视频填满休息。", "Move away from your seat and avoid filling the break with short videos."),
    studyCase(83, "关闭一次学习通知", "Mute notifications during study", "在学习时段暂停无关消息提醒。", "Pause unrelated alerts during the study period."),
    studyCase(84, "制定明天的学习任务", "Plan tomorrow's study task", "明确学习内容、开始时间和预计时长。", "Define the material, start time, and expected duration."),
    studyCase(85, "把学习任务拆成三步", "Break a study task into three steps", "分别写出准备、学习和复习阶段。", "Define the preparation, learning, and review stages."),
    studyCase(86, "检查本周学习进度", "Review this week's study progress", "对照计划，标出完成、延期和需要调整的内容。", "Compare against the plan and mark completed, delayed, and adjusted items."),
    studyCase(87, "记录一次专注中断", "Record one focus interruption", "写下干扰来源，并设计下次减少它的办法。", "Note the source of distraction and one way to reduce it next time."),
    studyCase(88, "整理下周学习材料", "Prepare next week's study materials", "提前收齐书籍、文件、链接和练习题。", "Gather books, files, links, and exercises in advance."),
    studyCase(89, "设定一个可衡量学习目标", "Set a measurable learning goal", "使用页数、题量、章节或测试结果定义完成。", "Define completion by pages, problems, chapters, or test results."),
    studyCase(90, "完成一次周度学习复盘", "Complete a weekly study review", "总结掌握内容、主要困难和下周调整。", "Summarize what you learned, major difficulties, and next week's changes."),
    studyCase(91, "制定七天阅读计划", "Create a seven-day reading plan", "把阅读内容分配到每天，并留出一天补进度。", "Divide the reading across the week and leave one catch-up day."),
    studyCase(92, "制定一周单词复习计划", "Create a weekly vocabulary review plan", "安排新词、旧词和自测的具体日期。", "Schedule new words, old words, and self-testing on specific days."),
    studyCase(93, "完成一组综合练习", "Complete a mixed practice set", "混合多个知识点，检验自己能否正确判断方法。", "Mix several topics to test whether you can choose the right method."),
    studyCase(94, "整理一个主题的知识体系", "Organize a topic knowledge system", "用目录、关系图和关键问题连接零散内容。", "Connect scattered material with an outline, map, and key questions."),
    studyCase(95, "比较两个不同观点", "Compare two different viewpoints", "分别写出双方论点、证据和可能的局限。", "List each side's claims, evidence, and possible limitations."),
    studyCase(96, "完成一次模拟测试", "Complete a practice test", "按正式时间完成，结束后分类分析错误。", "Use official timing and categorize errors afterward."),
    studyCase(97, "制定一个月学习路线", "Create a one-month learning path", "拆分每周主题、练习任务和检查节点。", "Divide the month into weekly topics, practice tasks, and checkpoints."),
    studyCase(98, "完成一次课程阶段总结", "Complete a course-stage summary", "整理已经掌握的内容、未解决问题和下一阶段目标。", "Organize mastered material, unresolved questions, and next-stage goals."),
    studyCase(99, "制作一份完整学习成果", "Create a complete learning artifact", "把所学内容转化为文章、演示、作品或讲解视频。", "Turn what you learned into an article, presentation, project, or teaching video."),
    studyCase(100, "完成一个月系统学习挑战", "Complete a one-month structured learning challenge", "每天学习并记录，按周复习，月底完成一次成果展示。", "Study and track daily, review weekly, and present a final result at month's end."),
)

private fun studyCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-study-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_study,
    imageAsset = "study",
)
