package com.luzalid.daka.recommendation

import com.luzalid.daka.R

internal fun workRecommendationCases(): List<RecommendationCase> = listOf(
    workCase(1, "整理办公桌面", "Tidy your desk", "收起无关物品，只留下当前工作需要的东西。", "Put away unrelated items and keep only what the current task needs."),
    workCase(2, "擦干净电脑屏幕", "Clean your computer screen", "使用合适的清洁工具，清除屏幕上的灰尘和指纹。", "Use suitable cleaning tools to remove dust and fingerprints."),
    workCase(3, "整理今天的待办列表", "Organize today's task list", "删除失效事项，并按重要程度重新排列任务。", "Remove outdated items and reorder tasks by importance."),
    workCase(4, "写下今天最重要的任务", "Write down today's top task", "只选一件最值得推进的事情，明确完成标准。", "Choose the single most valuable task and define what done means."),
    workCase(5, "完成一个五分钟任务", "Finish a five-minute task", "挑选一件很快能完成的小事，现在就把它处理掉。", "Choose a small task that can be finished quickly and do it now."),
    workCase(6, "关闭一个无用通知", "Disable one unnecessary notification", "减少一个会打断工作的应用通知。", "Turn off one app notification that interrupts your work."),
    workCase(7, "整理键盘旁的物品", "Clear the area beside your keyboard", "移开杯子、票据和杂物，为双手留出空间。", "Move cups, receipts, and clutter to leave room for your hands."),
    workCase(8, "给水杯加满水", "Fill your water bottle", "开始工作前准备好饮水，减少中途离开的次数。", "Prepare water before starting so you need fewer interruptions."),
    workCase(9, "检查一次工作日历", "Check your work calendar", "确认今天的会议、截止时间和预留时间。", "Review today's meetings, deadlines, and open time."),
    workCase(10, "准时开始第一项任务", "Start your first task on time", "到计划时间立即开始，不再继续准备或拖延。", "Begin at the planned time without extending preparation."),
    workCase(11, "专注工作十分钟", "Focus for ten minutes", "关闭无关页面，只处理眼前这一项工作。", "Close unrelated pages and work only on the current task."),
    workCase(12, "完成一次二十五分钟专注", "Complete a twenty-five-minute focus session", "设置计时器，在时间结束前避免切换任务。", "Set a timer and avoid switching tasks until it ends."),
    workCase(13, "清理五封旧邮件", "Clear five old emails", "回复、归档或删除五封不再需要停留在收件箱的邮件。", "Reply to, archive, or delete five emails from your inbox."),
    workCase(14, "回复一条搁置的消息", "Reply to a delayed message", "用简洁明确的内容处理一条等待回复的工作消息。", "Answer one waiting work message clearly and concisely."),
    workCase(15, "更新一个任务状态", "Update one task status", "在任务工具中记录最新进度和下一步。", "Record the latest progress and next step in your task tool."),
    workCase(16, "整理一个下载文件", "File one downloaded document", "把下载目录中的一个文件移动到正确位置并重新命名。", "Move one downloaded file to the right folder and rename it."),
    workCase(17, "删除一个重复文件", "Delete one duplicate file", "确认内容完全重复后，保留命名清晰的版本。", "After confirming they match, keep the clearly named version."),
    workCase(18, "记录一个工作灵感", "Capture one work idea", "把刚想到的点子写下来，并补充一个可执行步骤。", "Write down a new idea and add one actionable step."),
    workCase(19, "核对一次截止时间", "Verify one deadline", "确认日期、时间和时区，避免理解偏差。", "Confirm the date, time, and time zone to avoid confusion."),
    workCase(20, "结束一个闲置浏览器标签", "Close an unused browser tab", "关闭当前工作不需要的页面，减少视觉干扰。", "Close a page unrelated to your current work to reduce distraction."),
    workCase(21, "整理一个工作文件夹", "Organize one work folder", "按项目或日期归类文件，并移除明显无用的副本。", "Group files by project or date and remove obvious duplicates."),
    workCase(22, "为三个文件重新命名", "Rename three files", "使用包含内容和日期的名称，让文件更容易查找。", "Use names that include content and date so files are easier to find."),
    workCase(23, "建立一个项目资料夹", "Create a project folder", "为新项目建立清晰目录，存放文档、素材和输出。", "Create a clear structure for documents, assets, and output."),
    workCase(24, "归档一个已完成任务", "Archive one completed task", "确认结果已保存后，把完成事项移出当前列表。", "After saving the result, move the completed item out of the active list."),
    workCase(25, "整理一次桌面文件", "Organize desktop files", "把散落在电脑桌面的文件放回对应目录。", "Move loose desktop files into their proper folders."),
    workCase(26, "保存一份常用模板", "Save a reusable template", "把重复使用的文档整理成干净的模板。", "Turn a frequently reused document into a clean template."),
    workCase(27, "清理一次回收站", "Review the recycle bin", "检查其中内容，再清除确定不再需要的文件。", "Review its contents and remove files you no longer need."),
    workCase(28, "备份一份重要文档", "Back up an important document", "把重要文件保存到可靠的第二位置。", "Save an important file in a reliable second location."),
    workCase(29, "统一一组文件命名", "Standardize a set of filenames", "为同类文件采用一致的名称、日期和版本格式。", "Use a consistent name, date, and version format for related files."),
    workCase(30, "制作一份文件索引", "Create a file index", "列出关键文件的位置和用途，方便团队查找。", "List key files, locations, and purposes for easier team access."),
    workCase(31, "把大任务拆成三步", "Break a large task into three steps", "写下开始、执行和交付阶段各要完成什么。", "Define what must happen in the start, execution, and delivery stages."),
    workCase(32, "为任务写完成标准", "Define task completion criteria", "明确需要交付的内容、质量和确认方式。", "Clarify the required output, quality, and approval method."),
    workCase(33, "估算一项任务的时间", "Estimate one task", "根据步骤给出合理时长，并留出少量缓冲。", "Estimate from the steps and include a small buffer."),
    workCase(34, "给任务设置开始时间", "Schedule a task start time", "把任务放进日历，而不只记录截止日期。", "Put the task on your calendar instead of noting only its deadline."),
    workCase(35, "取消一项低价值任务", "Cancel a low-value task", "确认它不再重要后，从列表中明确删除。", "Once it is no longer valuable, remove it from the list."),
    workCase(36, "推迟一项非紧急任务", "Reschedule a nonurgent task", "选择更合适的日期，并记录推迟原因。", "Choose a better date and note why the task moved."),
    workCase(37, "委派一项合适的任务", "Delegate an appropriate task", "说明目标、截止时间和对方可获得的支持。", "Explain the goal, deadline, and support available."),
    workCase(38, "为明天选出三项任务", "Choose three tasks for tomorrow", "提前确定明天最需要推进的三件事。", "Select the three things that most need progress tomorrow."),
    workCase(39, "安排一个不被打扰的时段", "Schedule an interruption-free block", "在日历中保留一段时间，用于需要思考的工作。", "Reserve calendar time for work that requires concentration."),
    workCase(40, "检查本周任务负荷", "Review this week's workload", "找出安排过满的日期，并提前调整任务。", "Find overloaded days and adjust tasks before they become a problem."),
    workCase(41, "提前阅读会议议程", "Read a meeting agenda", "了解会议目标，并准备一个需要讨论的问题。", "Understand the meeting goal and prepare one question."),
    workCase(42, "为会议写一个目标", "Set one meeting objective", "明确会议结束时最希望获得的结果。", "Define the result you most want by the end of the meeting."),
    workCase(43, "准时进入线上会议", "Join an online meeting on time", "提前检查链接、麦克风和网络连接。", "Check the link, microphone, and connection in advance."),
    workCase(44, "记录三条会议结论", "Record three meeting decisions", "只写清已经确定的事项，不混入未决讨论。", "Capture confirmed decisions without mixing in unresolved discussion."),
    workCase(45, "写下会议行动项", "Write meeting action items", "为每项行动注明负责人和截止时间。", "Assign an owner and deadline to every action."),
    workCase(46, "发送一次会议摘要", "Send a meeting summary", "用简短内容同步结论、行动项和下一次节点。", "Briefly share decisions, actions, and the next checkpoint."),
    workCase(47, "取消一次无必要会议", "Cancel an unnecessary meeting", "如果异步沟通足够，就释放参会者的时间。", "Free everyone's time when asynchronous communication is enough."),
    workCase(48, "把讨论转成书面问题", "Turn a discussion into a written question", "补充背景、限制和期望结果，让别人容易回答。", "Include context, constraints, and the desired result for an easy response."),
    workCase(49, "会议中主动澄清一次", "Clarify one point in a meeting", "发现理解不一致时，用具体问题确认含义。", "Ask a specific question when people appear to understand something differently."),
    workCase(50, "会后更新项目记录", "Update project notes after a meeting", "把新决定和变化同步到团队共同使用的位置。", "Add new decisions and changes to the team's shared source."),
    workCase(51, "礼貌拒绝一个不合理请求", "Decline an unreasonable request politely", "说明当前限制，并给出可行的替代方案。", "Explain the constraint and offer a practical alternative."),
    workCase(52, "向同事表达一次感谢", "Thank a colleague", "具体说明对方的哪项帮助产生了价值。", "Mention exactly which help from the colleague was valuable."),
    workCase(53, "主动同步一次风险", "Share one risk early", "说明风险、可能影响以及建议的处理方式。", "Describe the risk, possible impact, and a suggested response."),
    workCase(54, "请求一次明确反馈", "Ask for specific feedback", "指出希望对方重点评价的内容，避免问题过于宽泛。", "Point to the area you want reviewed instead of asking too broadly."),
    workCase(55, "给出一次具体反馈", "Give specific feedback", "描述观察到的行为、影响和可行建议。", "Describe the observed behavior, its impact, and a practical suggestion."),
    workCase(56, "确认一次需求理解", "Confirm your understanding of a request", "用自己的话复述目标和限制，请对方确认。", "Restate the goal and constraints in your own words for confirmation."),
    workCase(57, "通知一次进度变化", "Communicate a schedule change", "尽早说明变化原因、影响和新的预计时间。", "Share the reason, impact, and revised estimate as early as possible."),
    workCase(58, "向新人解释一个流程", "Explain one process to a newcomer", "按顺序说明操作步骤，并指出常见错误。", "Explain the steps in order and mention common mistakes."),
    workCase(59, "整理一条团队公告", "Write a clear team announcement", "把背景、变化和需要执行的动作写清楚。", "Clearly state the context, change, and required action."),
    workCase(60, "解决一个沟通遗漏", "Resolve one communication gap", "找到未被同步的人，补充必要背景和最新结论。", "Find who was left out and share the needed context and latest decision."),
    workCase(61, "检查一份文档的标题", "Review a document title", "让标题准确说明内容，而不是使用模糊名称。", "Make the title describe the content instead of using a vague label."),
    workCase(62, "修改一段模糊说明", "Rewrite one unclear paragraph", "删掉歧义表达，补充必要条件和具体动作。", "Remove ambiguity and add necessary conditions and actions."),
    workCase(63, "为文档补充目录", "Add a table of contents", "给较长文档增加清晰结构，方便快速定位。", "Add structure to a long document so readers can navigate quickly."),
    workCase(64, "检查一次数据来源", "Verify one data source", "确认数据的时间、范围和原始出处。", "Confirm the data's date, scope, and original source."),
    workCase(65, "核对一个计算结果", "Check one calculation", "重新检查输入、公式和单位是否一致。", "Recheck the inputs, formula, and units for consistency."),
    workCase(66, "为图表补充说明", "Add context to a chart", "写清指标含义、时间范围和需要关注的结论。", "Explain the metric, time range, and key takeaway."),
    workCase(67, "精简一页演示文稿", "Simplify one presentation slide", "删除次要内容，只保留一个主要观点。", "Remove secondary details and keep one main point."),
    workCase(68, "检查一次拼写和格式", "Check spelling and formatting", "通读一份短文档，修正明显错误和不一致。", "Review a short document and fix obvious errors and inconsistencies."),
    workCase(69, "为交付物添加版本号", "Add a version number", "使用明确版本和日期，避免发送错误文件。", "Use a clear version and date to avoid sharing the wrong file."),
    workCase(70, "请同事审阅关键内容", "Ask a colleague to review key work", "说明需要检查的重点和反馈截止时间。", "Explain what needs checking and when feedback is needed."),
    workCase(71, "简化一个重复步骤", "Simplify one repeated step", "找出流程中可以合并或取消的一步。", "Find one step in a process that can be combined or removed."),
    workCase(72, "创建一个常用快捷方式", "Create a useful shortcut", "为经常打开的文件、页面或命令设置快捷入口。", "Add quick access to a frequently used file, page, or command."),
    workCase(73, "写一份操作检查清单", "Write an operating checklist", "把容易遗漏的关键步骤按执行顺序列出。", "List easily missed steps in the order they should happen."),
    workCase(74, "自动化一次重复操作", "Automate one repetitive action", "选择规则稳定的小任务，用现有工具减少手动处理。", "Use existing tools to reduce manual work on a stable repetitive task."),
    workCase(75, "记录一次故障处理过程", "Document one troubleshooting process", "写下现象、原因、解决办法和验证结果。", "Record the symptom, cause, solution, and verification result."),
    workCase(76, "清理一个过时模板", "Retire an outdated template", "标记或删除旧模板，并告知团队使用新版本。", "Mark or remove the old template and direct the team to the new one."),
    workCase(77, "减少一次重复录入", "Remove one duplicate data entry", "找到可以复用或导入的数据，避免再次手工输入。", "Reuse or import existing data instead of entering it again."),
    workCase(78, "为流程增加一个校验点", "Add a process check", "在容易出错的位置增加简单明确的检查。", "Add a simple, clear check at a common failure point."),
    workCase(79, "测量一项工作的实际用时", "Measure actual task time", "记录开始和结束时间，与原先估算进行比较。", "Record start and finish times and compare them with the estimate."),
    workCase(80, "优化一个交接步骤", "Improve one handoff", "明确交付内容、接收人和确认方式。", "Clarify what is handed over, who receives it, and how it is confirmed."),
    workCase(81, "复盘今天完成的工作", "Review today's completed work", "列出已完成事项，并记录一项值得保留的做法。", "List completed items and one practice worth repeating."),
    workCase(82, "记录一个未完成原因", "Record why one task remains unfinished", "区分时间不足、依赖阻塞或目标不清。", "Identify whether time, dependency, or unclear goals caused the delay."),
    workCase(83, "写下明天的第一步", "Write tomorrow's first step", "为最重要的任务留下一个可以立即开始的动作。", "Leave one immediately actionable step for tomorrow's top task."),
    workCase(84, "完成一次周度复盘", "Complete a weekly review", "回顾成果、问题和下周最需要关注的事情。", "Review outcomes, problems, and next week's main focus."),
    workCase(85, "整理本周工作成果", "Summarize this week's results", "用数据或具体交付物说明本周产生的进展。", "Use data or concrete deliverables to show the week's progress."),
    workCase(86, "分析一次时间偏差", "Analyze one schedule variance", "比较预计和实际用时，找出偏差产生的位置。", "Compare estimated and actual time to find where the difference arose."),
    workCase(87, "找出本周最大干扰", "Identify the week's biggest distraction", "记录它出现的原因，并设计一个减少干扰的方法。", "Note why it occurred and design one way to reduce it."),
    workCase(88, "总结一次成功经验", "Summarize one success", "写清采取了什么行动，以及它为什么有效。", "Describe what action worked and why it was effective."),
    workCase(89, "记录一次错误教训", "Document one lesson from a mistake", "聚焦可改进的流程，不把复盘变成责备。", "Focus on improving the process rather than assigning blame."),
    workCase(90, "清空本周临时记录", "Process this week's scratch notes", "把有价值内容归档，其余内容确认后删除。", "Archive useful notes and remove the rest after reviewing them."),
    workCase(91, "为项目画一张流程图", "Draw a project flowchart", "用节点和箭头表示主要步骤、判断和交付关系。", "Use nodes and arrows to show key steps, decisions, and handoffs."),
    workCase(92, "制定一个项目里程碑", "Define a project milestone", "明确日期、交付物和判断完成的标准。", "Set the date, deliverable, and completion criteria."),
    workCase(93, "建立一份项目风险清单", "Create a project risk list", "记录风险概率、影响和预防措施。", "Record each risk's likelihood, impact, and mitigation."),
    workCase(94, "规划下个月的工作重点", "Plan next month's priorities", "结合目标和资源，选出三项核心重点。", "Choose three core priorities based on goals and available resources."),
    workCase(95, "完成一次工作流程审计", "Audit a work process", "逐步检查耗时、重复、等待和容易出错的位置。", "Review each step for delays, duplication, waiting, and errors."),
    workCase(96, "为团队建立知识页面", "Create a team knowledge page", "集中整理常用链接、流程和问题答案。", "Collect common links, processes, and answers in one place."),
    workCase(97, "设计一套任务优先级规则", "Design task priority rules", "根据价值、紧急度、成本和依赖确定处理顺序。", "Order work using value, urgency, cost, and dependencies."),
    workCase(98, "制定一个季度成长目标", "Set a quarterly growth goal", "选择一项能力，定义练习方式和可衡量结果。", "Choose one skill and define practice methods and measurable results."),
    workCase(99, "完成一次项目结束复盘", "Complete a project retrospective", "总结目标结果、有效做法、问题和后续行动。", "Review goals, results, effective practices, problems, and follow-up actions."),
    workCase(100, "设计一周深度工作计划", "Design a deep-work week", "安排核心任务、专注时段、会议边界和每日复盘。", "Plan core tasks, focus blocks, meeting boundaries, and daily reviews."),
)

private fun workCase(
    number: Int,
    titleZh: String,
    titleEn: String,
    descriptionZh: String,
    descriptionEn: String,
) = RecommendationCase(
    id = "local-work-${number.toString().padStart(3, '0')}",
    title = text(titleZh, titleEn),
    description = text(descriptionZh, descriptionEn),
    categoryRes = R.string.category_work,
    imageAsset = "work",
)
